syntax = "proto3";

package wuk.net;

// 消息类型标志位
enum MessageType {
  NONE    = 0x00000000; // ........ ........ ........ ........ 无标志位（默认情况）
  FILE    = 0x00000001; // ........ ........ ........ .......1 文件
  DATA    = 0x00000002; // ........ ........ ........ ......1. 一般数据
  SEGMENT = 0x00000004; // ........ ........ ........ .....1.. 已分段
  OVER    = 0x00000008; // ........ ........ ........ ....1... 已是分段包的最后一个
  XCRYPT  = 0x00000010; // ........ ........ ........ ...1.... 已加密
  MESSAGE = 0x00000020; // ........ ........ ........ ..1..... 纯消息
  URGENT  = 0x00000040; // ........ ........ ........ .1...... 紧急包
  IMAGE   = 0x00000080; // ........ ........ ........ 1....... 图像且FILE，否则视为表情包
  VIDEO   = 0x00000100; // ........ ........ .......1 ........ 视频
  AUDIO   = 0x00000200; // ........ ........ ......1. ........ 音频
  ANYM    = 0x00000400; // ........ ........ .....1.. ........ 匿名包
}

// 主消息结构
message WukPacket {
  // 头部字段
  MessageType msg_type     = 1; // 消息类型标志位
  uint32      msg_seq      = 2; // 序列号
  uint32      seg_id       = 3; // 分段包ID
  uint32      proto_ver    = 4; // 协议版本号

  // 消息标识
  uint64      msg_id       = 5; // 消息唯一ID（使用fixed64保证精确存储）
  uint64      msg_size     = 6; // 消息体长度

  // 参与者
  uint64      sender_id    = 7; // 发送方ID（最高位可标记群聊）
  uint64      recipient_id = 8; // 接收方ID

  // 元数据
  double      time_stamp   = 9; // UNIX时间戳

  // 消息体
  bytes       message      = 10; // 二进制消息体（对应原wuk::Buffer）
}
