syntax = "proto3";

package wuk.im;

// 消息类型标志位（Bit map）
enum MessageType {
    NONE    = 0x00000000; // ........ ........ ........ ........ 无标志位（默认情况）
    FILE    = 0x00000001; // ........ ........ ........ .......1 文件
    DATA    = 0x00000002; // ........ ........ ........ ......1. 一般数据（如需要临时传输的数据）
    SEGMENT = 0x00000004; // ........ ........ ........ .....1.. 包为分段包且不是最后一个
    OVER    = 0x00000008; // ........ ........ ........ ....1... 包为分段包且是最后一个（需存在SEGMENT位）
    XCRYPT  = 0x00000010; // ........ ........ ........ ...1.... 已加密（保持Message头部不要加密）
    MESSAGE = 0x00000020; // ........ ........ ........ ..1..... 纯消息（只包含消息，如用户发的文字）
    URGENT  = 0x00000040; // ........ ........ ........ .1...... 紧急包（特殊情况下使用，目前暂时不会使用）
    IMAGE   = 0x00000080; // ........ ........ ........ 1....... 图像，应同时存在FILE位（后续考虑是否应增加图像类型如静态和动态分类）。
    VIDEO   = 0x00000100; // ........ ........ .......1 ........ 视频
    AUDIO   = 0x00000200; // ........ ........ ......1. ........ 音频
    ANYM    = 0x00000400; // ........ ........ .....1.. ........ 匿名包
    GROUP   = 0x40000000; // .1...... ........ ........ ........ 群组聊天（涉及到服务端广播方法）
    PRIVACY = 0x20000000; // ..1..... ........ ........ ........ 私密聊天（在业务处理上不同于一般聊天，可同时存在其他所有标志位）
}

// 主消息结构
message Message {
    // 头部字段
    MessageType m_type       = 1; // 消息类型标志位
    uint32      m_sequence   = 2; // 序列号
    uint32      m_segment_id = 3; // 分段包ID（未分段时必须始终为0）
    uint32      m_proto_ver  = 4; // 协议版本号

    // 参与者
    uint64      m_sender     = 5; // 发送方ID
    uint64      m_recipient  = 6; // 接收方ID

    // 元数据
    double      m_timestamp  = 7; // UNIX时间戳

    // 消息标识
    uint32      m_length     = 8; // 消息体长度
    uint32      m_id         = 9; // 消息唯一ID（此处的ID表示​​identifier​而非identity）

    // 消息体
    bytes       m_content    = 10; // 二进制消息体（对应原wuk::Buffer）
}

/*
 * 0. 对于校验，必须使用 **Protobuf** 将内容全部打包后输出为二进制序列后直接计算整个二进制序列的校验值（不可分开数据计算）。
 * 1. `m_proto_ver`最低必须是 **0x01** （即0.1版本）。
 * 2. 当未实行包分段传输时，`m_segment_id`的值应始终为 **0** 。
 * 2. `m_sender`和`m_recipient`即使在`m_type`为`ANYM`的情况下，也必须是准确的用户ID，不能匿名；
      当然在用户端可显示为匿名，需保留追踪到用户的能力。
 * 3. `m_timestamp`必须是UNIX时间戳，且格式必须是浮点数且至少保留3位小数，如`1728856869.7596`。
 * 4. `m_id`可由用户定义，若未定义则使用整个包的CRC32校验值；
      暂时不调整`m_id`的大小，因业务还未达到需要使用uint64的程度。
*/
