syntax = "proto3";

package wuk.im;

// 包的总类型
enum RequestType {
    HEARTBEAT      = 0;  // 心跳
    LOGIN          = 10; // 登录
    REGISTER       = 11; // 注册
    FIND_PWD       = 12; // 找回密码
    MESSAGE        = 20; // 发送消息
    FILE           = 21; // 文件传输
}

// 基本请求包构成
message BaseRequest {
    RequestType m_type      = 1; // 请求类型：LOGIN, REGISTER, SEND_MSG等
    double      m_timestamp = 2; // 时间戳（毫秒）
    uint32      m_id        = 3; // 唯一ID（此处的ID表示​ ​identifier ​而非 identity ）
    uint32      m_sequence  = 4; // 序列号
    uint32      m_segment   = 5; // 分段包ID
    uint32      m_proto_ver = 6; // 协议版本
}

