// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_response.proto

#include "common/includes/proto/login_response.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace wuk {
namespace im {
namespace auth {
PROTOBUF_CONSTEXPR UserInfo::UserInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.m_profile_picture_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_username_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_bio_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UserInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserInfoDefaultTypeInternal() {}
  union {
    UserInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserInfoDefaultTypeInternal _UserInfo_default_instance_;
PROTOBUF_CONSTEXPR LoginResponse::LoginResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.m_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_token_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_base_)*/nullptr
  , /*decltype(_impl_.m_user_)*/nullptr
  , /*decltype(_impl_.m_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LoginResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginResponseDefaultTypeInternal() {}
  union {
    LoginResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginResponseDefaultTypeInternal _LoginResponse_default_instance_;
}  // namespace auth
}  // namespace im
}  // namespace wuk
static ::_pb::Metadata file_level_metadata_login_5fresponse_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_login_5fresponse_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_login_5fresponse_2eproto = nullptr;

const uint32_t TableStruct_login_5fresponse_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::UserInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::UserInfo, _impl_.m_profile_picture_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::UserInfo, _impl_.m_username_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::UserInfo, _impl_.m_bio_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginResponse, _impl_.m_base_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginResponse, _impl_.m_code_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginResponse, _impl_.m_message_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginResponse, _impl_.m_token_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginResponse, _impl_.m_user_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::wuk::im::auth::UserInfo)},
  { 9, -1, -1, sizeof(::wuk::im::auth::LoginResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::wuk::im::auth::_UserInfo_default_instance_._instance,
  &::wuk::im::auth::_LoginResponse_default_instance_._instance,
};

const char descriptor_table_protodef_login_5fresponse_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024login_response.proto\022\013wuk.im.auth\032\014pac"
  "ket.proto\"H\n\010UserInfo\022\031\n\021m_profile_pictu"
  "re\030\001 \001(\t\022\022\n\nm_username\030\002 \001(\t\022\r\n\005m_bio\030\003 "
  "\001(\t\"\257\001\n\rLoginResponse\022(\n\006m_base\030\001 \001(\0132\030."
  "wuk.im.base.BaseRequest\022)\n\006m_code\030\002 \001(\0162"
  "\031.wuk.im.auth.ResponseType\022\021\n\tm_message\030"
  "\003 \001(\t\022\017\n\007m_token\030\004 \001(\t\022%\n\006m_user\030\005 \001(\0132\025"
  ".wuk.im.auth.UserInfo*\300\001\n\014ResponseType\022\031"
  "\n\025RESPONSE_TYPE_SUCCESS\020\000\022\030\n\024RESPONSE_TY"
  "PE_FAILED\020\001\022\035\n\031RESPONSE_TYPE_AUTH_FAILED"
  "\020\002\022\033\n\027RESPONSE_TYPE_NOT_FOUND\020\003\022\037\n\033RESPO"
  "NSE_TYPE_TOKEN_EXPIRED\020\004\022\036\n\032RESPONSE_TYP"
  "E_WAITWAITWAIT\020\005b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_login_5fresponse_2eproto_deps[1] = {
  &::descriptor_table_packet_2eproto,
};
static ::_pbi::once_flag descriptor_table_login_5fresponse_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_login_5fresponse_2eproto = {
    false, false, 504, descriptor_table_protodef_login_5fresponse_2eproto,
    "login_response.proto",
    &descriptor_table_login_5fresponse_2eproto_once, descriptor_table_login_5fresponse_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_login_5fresponse_2eproto::offsets,
    file_level_metadata_login_5fresponse_2eproto, file_level_enum_descriptors_login_5fresponse_2eproto,
    file_level_service_descriptors_login_5fresponse_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_login_5fresponse_2eproto_getter() {
  return &descriptor_table_login_5fresponse_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_login_5fresponse_2eproto(&descriptor_table_login_5fresponse_2eproto);
namespace wuk {
namespace im {
namespace auth {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResponseType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_login_5fresponse_2eproto);
  return file_level_enum_descriptors_login_5fresponse_2eproto[0];
}
bool ResponseType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class UserInfo::_Internal {
 public:
};

UserInfo::UserInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:wuk.im.auth.UserInfo)
}
UserInfo::UserInfo(const UserInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UserInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.m_profile_picture_){}
    , decltype(_impl_.m_username_){}
    , decltype(_impl_.m_bio_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.m_profile_picture_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_profile_picture_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_profile_picture().empty()) {
    _this->_impl_.m_profile_picture_.Set(from._internal_m_profile_picture(), 
      _this->GetArenaForAllocation());
  }
  _impl_.m_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_username().empty()) {
    _this->_impl_.m_username_.Set(from._internal_m_username(), 
      _this->GetArenaForAllocation());
  }
  _impl_.m_bio_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_bio_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_bio().empty()) {
    _this->_impl_.m_bio_.Set(from._internal_m_bio(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:wuk.im.auth.UserInfo)
}

inline void UserInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.m_profile_picture_){}
    , decltype(_impl_.m_username_){}
    , decltype(_impl_.m_bio_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.m_profile_picture_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_profile_picture_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.m_username_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_username_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.m_bio_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_bio_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UserInfo::~UserInfo() {
  // @@protoc_insertion_point(destructor:wuk.im.auth.UserInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UserInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.m_profile_picture_.Destroy();
  _impl_.m_username_.Destroy();
  _impl_.m_bio_.Destroy();
}

void UserInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UserInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:wuk.im.auth.UserInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.m_profile_picture_.ClearToEmpty();
  _impl_.m_username_.ClearToEmpty();
  _impl_.m_bio_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UserInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string m_profile_picture = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_m_profile_picture();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.auth.UserInfo.m_profile_picture"));
        } else
          goto handle_unusual;
        continue;
      // string m_username = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_m_username();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.auth.UserInfo.m_username"));
        } else
          goto handle_unusual;
        continue;
      // string m_bio = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_m_bio();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.auth.UserInfo.m_bio"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UserInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:wuk.im.auth.UserInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string m_profile_picture = 1;
  if (!this->_internal_m_profile_picture().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_m_profile_picture().data(), static_cast<int>(this->_internal_m_profile_picture().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.auth.UserInfo.m_profile_picture");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_m_profile_picture(), target);
  }

  // string m_username = 2;
  if (!this->_internal_m_username().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_m_username().data(), static_cast<int>(this->_internal_m_username().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.auth.UserInfo.m_username");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_m_username(), target);
  }

  // string m_bio = 3;
  if (!this->_internal_m_bio().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_m_bio().data(), static_cast<int>(this->_internal_m_bio().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.auth.UserInfo.m_bio");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_m_bio(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:wuk.im.auth.UserInfo)
  return target;
}

size_t UserInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wuk.im.auth.UserInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string m_profile_picture = 1;
  if (!this->_internal_m_profile_picture().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_m_profile_picture());
  }

  // string m_username = 2;
  if (!this->_internal_m_username().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_m_username());
  }

  // string m_bio = 3;
  if (!this->_internal_m_bio().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_m_bio());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UserInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UserInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UserInfo::GetClassData() const { return &_class_data_; }


void UserInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UserInfo*>(&to_msg);
  auto& from = static_cast<const UserInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wuk.im.auth.UserInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_m_profile_picture().empty()) {
    _this->_internal_set_m_profile_picture(from._internal_m_profile_picture());
  }
  if (!from._internal_m_username().empty()) {
    _this->_internal_set_m_username(from._internal_m_username());
  }
  if (!from._internal_m_bio().empty()) {
    _this->_internal_set_m_bio(from._internal_m_bio());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UserInfo::CopyFrom(const UserInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wuk.im.auth.UserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserInfo::IsInitialized() const {
  return true;
}

void UserInfo::InternalSwap(UserInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_profile_picture_, lhs_arena,
      &other->_impl_.m_profile_picture_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_username_, lhs_arena,
      &other->_impl_.m_username_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_bio_, lhs_arena,
      &other->_impl_.m_bio_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata UserInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_login_5fresponse_2eproto_getter, &descriptor_table_login_5fresponse_2eproto_once,
      file_level_metadata_login_5fresponse_2eproto[0]);
}

// ===================================================================

class LoginResponse::_Internal {
 public:
  static const ::wuk::im::base::BaseRequest& m_base(const LoginResponse* msg);
  static const ::wuk::im::auth::UserInfo& m_user(const LoginResponse* msg);
};

const ::wuk::im::base::BaseRequest&
LoginResponse::_Internal::m_base(const LoginResponse* msg) {
  return *msg->_impl_.m_base_;
}
const ::wuk::im::auth::UserInfo&
LoginResponse::_Internal::m_user(const LoginResponse* msg) {
  return *msg->_impl_.m_user_;
}
void LoginResponse::clear_m_base() {
  if (GetArenaForAllocation() == nullptr && _impl_.m_base_ != nullptr) {
    delete _impl_.m_base_;
  }
  _impl_.m_base_ = nullptr;
}
LoginResponse::LoginResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:wuk.im.auth.LoginResponse)
}
LoginResponse::LoginResponse(const LoginResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LoginResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.m_message_){}
    , decltype(_impl_.m_token_){}
    , decltype(_impl_.m_base_){nullptr}
    , decltype(_impl_.m_user_){nullptr}
    , decltype(_impl_.m_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.m_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_message().empty()) {
    _this->_impl_.m_message_.Set(from._internal_m_message(), 
      _this->GetArenaForAllocation());
  }
  _impl_.m_token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_token().empty()) {
    _this->_impl_.m_token_.Set(from._internal_m_token(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_m_base()) {
    _this->_impl_.m_base_ = new ::wuk::im::base::BaseRequest(*from._impl_.m_base_);
  }
  if (from._internal_has_m_user()) {
    _this->_impl_.m_user_ = new ::wuk::im::auth::UserInfo(*from._impl_.m_user_);
  }
  _this->_impl_.m_code_ = from._impl_.m_code_;
  // @@protoc_insertion_point(copy_constructor:wuk.im.auth.LoginResponse)
}

inline void LoginResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.m_message_){}
    , decltype(_impl_.m_token_){}
    , decltype(_impl_.m_base_){nullptr}
    , decltype(_impl_.m_user_){nullptr}
    , decltype(_impl_.m_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.m_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.m_token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LoginResponse::~LoginResponse() {
  // @@protoc_insertion_point(destructor:wuk.im.auth.LoginResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LoginResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.m_message_.Destroy();
  _impl_.m_token_.Destroy();
  if (this != internal_default_instance()) delete _impl_.m_base_;
  if (this != internal_default_instance()) delete _impl_.m_user_;
}

void LoginResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LoginResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:wuk.im.auth.LoginResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.m_message_.ClearToEmpty();
  _impl_.m_token_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.m_base_ != nullptr) {
    delete _impl_.m_base_;
  }
  _impl_.m_base_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.m_user_ != nullptr) {
    delete _impl_.m_user_;
  }
  _impl_.m_user_ = nullptr;
  _impl_.m_code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LoginResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .wuk.im.base.BaseRequest m_base = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_m_base(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .wuk.im.auth.ResponseType m_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_m_code(static_cast<::wuk::im::auth::ResponseType>(val));
        } else
          goto handle_unusual;
        continue;
      // string m_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_m_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.auth.LoginResponse.m_message"));
        } else
          goto handle_unusual;
        continue;
      // string m_token = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_m_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.auth.LoginResponse.m_token"));
        } else
          goto handle_unusual;
        continue;
      // .wuk.im.auth.UserInfo m_user = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_m_user(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LoginResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:wuk.im.auth.LoginResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .wuk.im.base.BaseRequest m_base = 1;
  if (this->_internal_has_m_base()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::m_base(this),
        _Internal::m_base(this).GetCachedSize(), target, stream);
  }

  // .wuk.im.auth.ResponseType m_code = 2;
  if (this->_internal_m_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_m_code(), target);
  }

  // string m_message = 3;
  if (!this->_internal_m_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_m_message().data(), static_cast<int>(this->_internal_m_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.auth.LoginResponse.m_message");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_m_message(), target);
  }

  // string m_token = 4;
  if (!this->_internal_m_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_m_token().data(), static_cast<int>(this->_internal_m_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.auth.LoginResponse.m_token");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_m_token(), target);
  }

  // .wuk.im.auth.UserInfo m_user = 5;
  if (this->_internal_has_m_user()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::m_user(this),
        _Internal::m_user(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:wuk.im.auth.LoginResponse)
  return target;
}

size_t LoginResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wuk.im.auth.LoginResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string m_message = 3;
  if (!this->_internal_m_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_m_message());
  }

  // string m_token = 4;
  if (!this->_internal_m_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_m_token());
  }

  // .wuk.im.base.BaseRequest m_base = 1;
  if (this->_internal_has_m_base()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.m_base_);
  }

  // .wuk.im.auth.UserInfo m_user = 5;
  if (this->_internal_has_m_user()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.m_user_);
  }

  // .wuk.im.auth.ResponseType m_code = 2;
  if (this->_internal_m_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_m_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LoginResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LoginResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LoginResponse::GetClassData() const { return &_class_data_; }


void LoginResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LoginResponse*>(&to_msg);
  auto& from = static_cast<const LoginResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wuk.im.auth.LoginResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_m_message().empty()) {
    _this->_internal_set_m_message(from._internal_m_message());
  }
  if (!from._internal_m_token().empty()) {
    _this->_internal_set_m_token(from._internal_m_token());
  }
  if (from._internal_has_m_base()) {
    _this->_internal_mutable_m_base()->::wuk::im::base::BaseRequest::MergeFrom(
        from._internal_m_base());
  }
  if (from._internal_has_m_user()) {
    _this->_internal_mutable_m_user()->::wuk::im::auth::UserInfo::MergeFrom(
        from._internal_m_user());
  }
  if (from._internal_m_code() != 0) {
    _this->_internal_set_m_code(from._internal_m_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LoginResponse::CopyFrom(const LoginResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wuk.im.auth.LoginResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginResponse::IsInitialized() const {
  return true;
}

void LoginResponse::InternalSwap(LoginResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_message_, lhs_arena,
      &other->_impl_.m_message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_token_, lhs_arena,
      &other->_impl_.m_token_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.m_code_)
      + sizeof(LoginResponse::_impl_.m_code_)
      - PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.m_base_)>(
          reinterpret_cast<char*>(&_impl_.m_base_),
          reinterpret_cast<char*>(&other->_impl_.m_base_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LoginResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_login_5fresponse_2eproto_getter, &descriptor_table_login_5fresponse_2eproto_once,
      file_level_metadata_login_5fresponse_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace auth
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::wuk::im::auth::UserInfo*
Arena::CreateMaybeMessage< ::wuk::im::auth::UserInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::wuk::im::auth::UserInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::wuk::im::auth::LoginResponse*
Arena::CreateMaybeMessage< ::wuk::im::auth::LoginResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::wuk::im::auth::LoginResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
