// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_request.proto

#include "common/includes/proto/login_request.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace wuk {
namespace im {
namespace auth {
PROTOBUF_CONSTEXPR LoginRequest::LoginRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.m_account_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_base_)*/nullptr
  , /*decltype(_impl_.credential_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct LoginRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginRequestDefaultTypeInternal() {}
  union {
    LoginRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginRequestDefaultTypeInternal _LoginRequest_default_instance_;
}  // namespace auth
}  // namespace im
}  // namespace wuk
static ::_pb::Metadata file_level_metadata_login_5frequest_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_login_5frequest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_login_5frequest_2eproto = nullptr;

const uint32_t TableStruct_login_5frequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginRequest, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginRequest, _impl_.m_base_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginRequest, _impl_.m_account_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::auth::LoginRequest, _impl_.credential_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::wuk::im::auth::LoginRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::wuk::im::auth::_LoginRequest_default_instance_._instance,
};

const char descriptor_table_protodef_login_5frequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023login_request.proto\022\013wuk.im.auth\032\014pack"
  "et.proto\"\222\001\n\014LoginRequest\022(\n\006m_base\030\001 \001("
  "\0132\030.wuk.im.base.BaseRequest\022\022\n\010password\030"
  "\003 \001(\tH\000\022\017\n\005token\030\004 \001(\tH\000\022\022\n\010sms_code\030\005 \001"
  "(\tH\000\022\021\n\tm_account\030\002 \001(\tB\014\n\ncredentialb\006p"
  "roto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_login_5frequest_2eproto_deps[1] = {
  &::descriptor_table_packet_2eproto,
};
static ::_pbi::once_flag descriptor_table_login_5frequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_login_5frequest_2eproto = {
    false, false, 205, descriptor_table_protodef_login_5frequest_2eproto,
    "login_request.proto",
    &descriptor_table_login_5frequest_2eproto_once, descriptor_table_login_5frequest_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_login_5frequest_2eproto::offsets,
    file_level_metadata_login_5frequest_2eproto, file_level_enum_descriptors_login_5frequest_2eproto,
    file_level_service_descriptors_login_5frequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_login_5frequest_2eproto_getter() {
  return &descriptor_table_login_5frequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_login_5frequest_2eproto(&descriptor_table_login_5frequest_2eproto);
namespace wuk {
namespace im {
namespace auth {

// ===================================================================

class LoginRequest::_Internal {
 public:
  static const ::wuk::im::base::BaseRequest& m_base(const LoginRequest* msg);
};

const ::wuk::im::base::BaseRequest&
LoginRequest::_Internal::m_base(const LoginRequest* msg) {
  return *msg->_impl_.m_base_;
}
void LoginRequest::clear_m_base() {
  if (GetArenaForAllocation() == nullptr && _impl_.m_base_ != nullptr) {
    delete _impl_.m_base_;
  }
  _impl_.m_base_ = nullptr;
}
LoginRequest::LoginRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:wuk.im.auth.LoginRequest)
}
LoginRequest::LoginRequest(const LoginRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LoginRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.m_account_){}
    , decltype(_impl_.m_base_){nullptr}
    , decltype(_impl_.credential_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.m_account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_account_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_account().empty()) {
    _this->_impl_.m_account_.Set(from._internal_m_account(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_m_base()) {
    _this->_impl_.m_base_ = new ::wuk::im::base::BaseRequest(*from._impl_.m_base_);
  }
  clear_has_credential();
  switch (from.credential_case()) {
    case kPassword: {
      _this->_internal_set_password(from._internal_password());
      break;
    }
    case kToken: {
      _this->_internal_set_token(from._internal_token());
      break;
    }
    case kSmsCode: {
      _this->_internal_set_sms_code(from._internal_sms_code());
      break;
    }
    case CREDENTIAL_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:wuk.im.auth.LoginRequest)
}

inline void LoginRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.m_account_){}
    , decltype(_impl_.m_base_){nullptr}
    , decltype(_impl_.credential_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.m_account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_account_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_credential();
}

LoginRequest::~LoginRequest() {
  // @@protoc_insertion_point(destructor:wuk.im.auth.LoginRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LoginRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.m_account_.Destroy();
  if (this != internal_default_instance()) delete _impl_.m_base_;
  if (has_credential()) {
    clear_credential();
  }
}

void LoginRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LoginRequest::clear_credential() {
// @@protoc_insertion_point(one_of_clear_start:wuk.im.auth.LoginRequest)
  switch (credential_case()) {
    case kPassword: {
      _impl_.credential_.password_.Destroy();
      break;
    }
    case kToken: {
      _impl_.credential_.token_.Destroy();
      break;
    }
    case kSmsCode: {
      _impl_.credential_.sms_code_.Destroy();
      break;
    }
    case CREDENTIAL_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = CREDENTIAL_NOT_SET;
}


void LoginRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wuk.im.auth.LoginRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.m_account_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.m_base_ != nullptr) {
    delete _impl_.m_base_;
  }
  _impl_.m_base_ = nullptr;
  clear_credential();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LoginRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .wuk.im.base.BaseRequest m_base = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_m_base(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string m_account = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_m_account();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.auth.LoginRequest.m_account"));
        } else
          goto handle_unusual;
        continue;
      // string password = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_password();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.auth.LoginRequest.password"));
        } else
          goto handle_unusual;
        continue;
      // string token = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.auth.LoginRequest.token"));
        } else
          goto handle_unusual;
        continue;
      // string sms_code = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_sms_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.auth.LoginRequest.sms_code"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LoginRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:wuk.im.auth.LoginRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .wuk.im.base.BaseRequest m_base = 1;
  if (this->_internal_has_m_base()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::m_base(this),
        _Internal::m_base(this).GetCachedSize(), target, stream);
  }

  // string m_account = 2;
  if (!this->_internal_m_account().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_m_account().data(), static_cast<int>(this->_internal_m_account().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.auth.LoginRequest.m_account");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_m_account(), target);
  }

  // string password = 3;
  if (_internal_has_password()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_password().data(), static_cast<int>(this->_internal_password().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.auth.LoginRequest.password");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_password(), target);
  }

  // string token = 4;
  if (_internal_has_token()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_token().data(), static_cast<int>(this->_internal_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.auth.LoginRequest.token");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_token(), target);
  }

  // string sms_code = 5;
  if (_internal_has_sms_code()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sms_code().data(), static_cast<int>(this->_internal_sms_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.auth.LoginRequest.sms_code");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_sms_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:wuk.im.auth.LoginRequest)
  return target;
}

size_t LoginRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wuk.im.auth.LoginRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string m_account = 2;
  if (!this->_internal_m_account().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_m_account());
  }

  // .wuk.im.base.BaseRequest m_base = 1;
  if (this->_internal_has_m_base()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.m_base_);
  }

  switch (credential_case()) {
    // string password = 3;
    case kPassword: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_password());
      break;
    }
    // string token = 4;
    case kToken: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_token());
      break;
    }
    // string sms_code = 5;
    case kSmsCode: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_sms_code());
      break;
    }
    case CREDENTIAL_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LoginRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LoginRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LoginRequest::GetClassData() const { return &_class_data_; }


void LoginRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LoginRequest*>(&to_msg);
  auto& from = static_cast<const LoginRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wuk.im.auth.LoginRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_m_account().empty()) {
    _this->_internal_set_m_account(from._internal_m_account());
  }
  if (from._internal_has_m_base()) {
    _this->_internal_mutable_m_base()->::wuk::im::base::BaseRequest::MergeFrom(
        from._internal_m_base());
  }
  switch (from.credential_case()) {
    case kPassword: {
      _this->_internal_set_password(from._internal_password());
      break;
    }
    case kToken: {
      _this->_internal_set_token(from._internal_token());
      break;
    }
    case kSmsCode: {
      _this->_internal_set_sms_code(from._internal_sms_code());
      break;
    }
    case CREDENTIAL_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LoginRequest::CopyFrom(const LoginRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wuk.im.auth.LoginRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginRequest::IsInitialized() const {
  return true;
}

void LoginRequest::InternalSwap(LoginRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_account_, lhs_arena,
      &other->_impl_.m_account_, rhs_arena
  );
  swap(_impl_.m_base_, other->_impl_.m_base_);
  swap(_impl_.credential_, other->_impl_.credential_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata LoginRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_login_5frequest_2eproto_getter, &descriptor_table_login_5frequest_2eproto_once,
      file_level_metadata_login_5frequest_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace auth
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::wuk::im::auth::LoginRequest*
Arena::CreateMaybeMessage< ::wuk::im::auth::LoginRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::wuk::im::auth::LoginRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
