// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#include "common/includes/proto/message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace wuk {
namespace im {
namespace msg {
PROTOBUF_CONSTEXPR Message::Message(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.m_content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_base_)*/nullptr
  , /*decltype(_impl_.m_msg_type_)*/0
  , /*decltype(_impl_.m_chat_type_)*/0
  , /*decltype(_impl_.m_sender_)*/uint64_t{0u}
  , /*decltype(_impl_.target_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageDefaultTypeInternal() {}
  union {
    Message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace msg
}  // namespace im
}  // namespace wuk
static ::_pb::Metadata file_level_metadata_message_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_message_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_message_2eproto = nullptr;

const uint32_t TableStruct_message_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::wuk::im::msg::Message, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::wuk::im::msg::Message, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::wuk::im::msg::Message, _impl_.m_base_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::msg::Message, _impl_.m_msg_type_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::msg::Message, _impl_.m_chat_type_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::msg::Message, _impl_.m_sender_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::wuk::im::msg::Message, _impl_.m_content_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::msg::Message, _impl_.target_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::wuk::im::msg::Message)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::wuk::im::msg::_Message_default_instance_._instance,
};

const char descriptor_table_protodef_message_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rmessage.proto\022\nwuk.im.msg\032\014packet.prot"
  "o\"\344\001\n\007Message\022(\n\006m_base\030\001 \001(\0132\030.wuk.im.b"
  "ase.BaseRequest\022+\n\nm_msg_type\030\002 \001(\0162\027.wu"
  "k.im.msg.MessageType\022)\n\013m_chat_type\030\003 \001("
  "\0162\024.wuk.im.msg.ChatType\022\020\n\010m_sender\030\004 \001("
  "\004\022\025\n\013m_recipient\030\005 \001(\004H\000\022\021\n\007m_group\030\006 \001("
  "\004H\000\022\021\n\tm_content\030\007 \001(\014B\010\n\006target*k\n\013Mess"
  "ageType\022\025\n\021MESSAGE_TYPE_TEXT\020\000\022\026\n\022MESSAG"
  "E_TYPE_IMAGE\020\001\022\026\n\022MESSAGE_TYPE_VOICE\020\002\022\025"
  "\n\021MESSAGE_TYPE_FILE\020\004*M\n\010ChatType\022\025\n\021CHA"
  "T_TYPE_PRIVATE\020\000\022\023\n\017CHAT_TYPE_GROUP\020\001\022\025\n"
  "\021CHAT_TYPE_ONE2ONE\020\002b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_message_2eproto_deps[1] = {
  &::descriptor_table_packet_2eproto,
};
static ::_pbi::once_flag descriptor_table_message_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_message_2eproto = {
    false, false, 468, descriptor_table_protodef_message_2eproto,
    "message.proto",
    &descriptor_table_message_2eproto_once, descriptor_table_message_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_message_2eproto::offsets,
    file_level_metadata_message_2eproto, file_level_enum_descriptors_message_2eproto,
    file_level_service_descriptors_message_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_message_2eproto_getter() {
  return &descriptor_table_message_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_message_2eproto(&descriptor_table_message_2eproto);
namespace wuk {
namespace im {
namespace msg {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_enum_descriptors_message_2eproto[0];
}
bool MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ChatType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_enum_descriptors_message_2eproto[1];
}
bool ChatType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Message::_Internal {
 public:
  static const ::wuk::im::base::BaseRequest& m_base(const Message* msg);
};

const ::wuk::im::base::BaseRequest&
Message::_Internal::m_base(const Message* msg) {
  return *msg->_impl_.m_base_;
}
void Message::clear_m_base() {
  if (GetArenaForAllocation() == nullptr && _impl_.m_base_ != nullptr) {
    delete _impl_.m_base_;
  }
  _impl_.m_base_ = nullptr;
}
Message::Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:wuk.im.msg.Message)
}
Message::Message(const Message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Message* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.m_content_){}
    , decltype(_impl_.m_base_){nullptr}
    , decltype(_impl_.m_msg_type_){}
    , decltype(_impl_.m_chat_type_){}
    , decltype(_impl_.m_sender_){}
    , decltype(_impl_.target_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.m_content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_content().empty()) {
    _this->_impl_.m_content_.Set(from._internal_m_content(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_m_base()) {
    _this->_impl_.m_base_ = new ::wuk::im::base::BaseRequest(*from._impl_.m_base_);
  }
  ::memcpy(&_impl_.m_msg_type_, &from._impl_.m_msg_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.m_sender_) -
    reinterpret_cast<char*>(&_impl_.m_msg_type_)) + sizeof(_impl_.m_sender_));
  clear_has_target();
  switch (from.target_case()) {
    case kMRecipient: {
      _this->_internal_set_m_recipient(from._internal_m_recipient());
      break;
    }
    case kMGroup: {
      _this->_internal_set_m_group(from._internal_m_group());
      break;
    }
    case TARGET_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:wuk.im.msg.Message)
}

inline void Message::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.m_content_){}
    , decltype(_impl_.m_base_){nullptr}
    , decltype(_impl_.m_msg_type_){0}
    , decltype(_impl_.m_chat_type_){0}
    , decltype(_impl_.m_sender_){uint64_t{0u}}
    , decltype(_impl_.target_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.m_content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_target();
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:wuk.im.msg.Message)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.m_content_.Destroy();
  if (this != internal_default_instance()) delete _impl_.m_base_;
  if (has_target()) {
    clear_target();
  }
}

void Message::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Message::clear_target() {
// @@protoc_insertion_point(one_of_clear_start:wuk.im.msg.Message)
  switch (target_case()) {
    case kMRecipient: {
      // No need to clear
      break;
    }
    case kMGroup: {
      // No need to clear
      break;
    }
    case TARGET_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = TARGET_NOT_SET;
}


void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:wuk.im.msg.Message)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.m_content_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.m_base_ != nullptr) {
    delete _impl_.m_base_;
  }
  _impl_.m_base_ = nullptr;
  ::memset(&_impl_.m_msg_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.m_sender_) -
      reinterpret_cast<char*>(&_impl_.m_msg_type_)) + sizeof(_impl_.m_sender_));
  clear_target();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Message::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .wuk.im.base.BaseRequest m_base = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_m_base(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .wuk.im.msg.MessageType m_msg_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_m_msg_type(static_cast<::wuk::im::msg::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // .wuk.im.msg.ChatType m_chat_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_m_chat_type(static_cast<::wuk::im::msg::ChatType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 m_sender = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.m_sender_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 m_recipient = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _internal_set_m_recipient(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 m_group = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _internal_set_m_group(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes m_content = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_m_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Message::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:wuk.im.msg.Message)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .wuk.im.base.BaseRequest m_base = 1;
  if (this->_internal_has_m_base()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::m_base(this),
        _Internal::m_base(this).GetCachedSize(), target, stream);
  }

  // .wuk.im.msg.MessageType m_msg_type = 2;
  if (this->_internal_m_msg_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_m_msg_type(), target);
  }

  // .wuk.im.msg.ChatType m_chat_type = 3;
  if (this->_internal_m_chat_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_m_chat_type(), target);
  }

  // uint64 m_sender = 4;
  if (this->_internal_m_sender() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_m_sender(), target);
  }

  // uint64 m_recipient = 5;
  if (_internal_has_m_recipient()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_m_recipient(), target);
  }

  // uint64 m_group = 6;
  if (_internal_has_m_group()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_m_group(), target);
  }

  // bytes m_content = 7;
  if (!this->_internal_m_content().empty()) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_m_content(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:wuk.im.msg.Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wuk.im.msg.Message)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes m_content = 7;
  if (!this->_internal_m_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_m_content());
  }

  // .wuk.im.base.BaseRequest m_base = 1;
  if (this->_internal_has_m_base()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.m_base_);
  }

  // .wuk.im.msg.MessageType m_msg_type = 2;
  if (this->_internal_m_msg_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_m_msg_type());
  }

  // .wuk.im.msg.ChatType m_chat_type = 3;
  if (this->_internal_m_chat_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_m_chat_type());
  }

  // uint64 m_sender = 4;
  if (this->_internal_m_sender() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_m_sender());
  }

  switch (target_case()) {
    // uint64 m_recipient = 5;
    case kMRecipient: {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_m_recipient());
      break;
    }
    // uint64 m_group = 6;
    case kMGroup: {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_m_group());
      break;
    }
    case TARGET_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Message::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Message::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Message::GetClassData() const { return &_class_data_; }


void Message::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Message*>(&to_msg);
  auto& from = static_cast<const Message&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wuk.im.msg.Message)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_m_content().empty()) {
    _this->_internal_set_m_content(from._internal_m_content());
  }
  if (from._internal_has_m_base()) {
    _this->_internal_mutable_m_base()->::wuk::im::base::BaseRequest::MergeFrom(
        from._internal_m_base());
  }
  if (from._internal_m_msg_type() != 0) {
    _this->_internal_set_m_msg_type(from._internal_m_msg_type());
  }
  if (from._internal_m_chat_type() != 0) {
    _this->_internal_set_m_chat_type(from._internal_m_chat_type());
  }
  if (from._internal_m_sender() != 0) {
    _this->_internal_set_m_sender(from._internal_m_sender());
  }
  switch (from.target_case()) {
    case kMRecipient: {
      _this->_internal_set_m_recipient(from._internal_m_recipient());
      break;
    }
    case kMGroup: {
      _this->_internal_set_m_group(from._internal_m_group());
      break;
    }
    case TARGET_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wuk.im.msg.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::InternalSwap(Message* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_content_, lhs_arena,
      &other->_impl_.m_content_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Message, _impl_.m_sender_)
      + sizeof(Message::_impl_.m_sender_)
      - PROTOBUF_FIELD_OFFSET(Message, _impl_.m_base_)>(
          reinterpret_cast<char*>(&_impl_.m_base_),
          reinterpret_cast<char*>(&other->_impl_.m_base_));
  swap(_impl_.target_, other->_impl_.target_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace msg
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::wuk::im::msg::Message*
Arena::CreateMaybeMessage< ::wuk::im::msg::Message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::wuk::im::msg::Message >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
