// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

#include "common/includes/proto/packet.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace wuk {
namespace im {
namespace base {
PROTOBUF_CONSTEXPR BaseRequest::BaseRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.m_type_)*/0
  , /*decltype(_impl_.m_id_)*/0u
  , /*decltype(_impl_.m_sequence_)*/0u
  , /*decltype(_impl_.m_segment_)*/0u
  , /*decltype(_impl_.m_timestamp_)*/uint64_t{0u}
  , /*decltype(_impl_.m_proto_ver_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BaseRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BaseRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BaseRequestDefaultTypeInternal() {}
  union {
    BaseRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BaseRequestDefaultTypeInternal _BaseRequest_default_instance_;
}  // namespace base
}  // namespace im
}  // namespace wuk
static ::_pb::Metadata file_level_metadata_packet_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_packet_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_packet_2eproto = nullptr;

const uint32_t TableStruct_packet_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::wuk::im::base::BaseRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::wuk::im::base::BaseRequest, _impl_.m_type_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::base::BaseRequest, _impl_.m_id_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::base::BaseRequest, _impl_.m_sequence_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::base::BaseRequest, _impl_.m_segment_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::base::BaseRequest, _impl_.m_proto_ver_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::base::BaseRequest, _impl_.m_timestamp_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::wuk::im::base::BaseRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::wuk::im::base::_BaseRequest_default_instance_._instance,
};

const char descriptor_table_protodef_packet_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014packet.proto\022\013wuk.im.base\"\226\001\n\013BaseRequ"
  "est\022(\n\006m_type\030\001 \001(\0162\030.wuk.im.base.Reques"
  "tType\022\014\n\004m_id\030\002 \001(\r\022\022\n\nm_sequence\030\003 \001(\r\022"
  "\021\n\tm_segment\030\004 \001(\r\022\023\n\013m_proto_ver\030\005 \001(\r\022"
  "\023\n\013m_timestamp\030\006 \001(\004*\221\001\n\013RequestType\022\032\n\026"
  "REQUEST_TYPE_HEARTBEAT\020\000\022\026\n\022REQUEST_TYPE"
  "_LOGIN\020\n\022\031\n\025REQUEST_TYPE_REGISTER\020\013\022\031\n\025R"
  "EQUEST_TYPE_FIND_PWD\020\014\022\030\n\024REQUEST_TYPE_M"
  "ESSAGE\020\024b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_packet_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_packet_2eproto = {
    false, false, 336, descriptor_table_protodef_packet_2eproto,
    "packet.proto",
    &descriptor_table_packet_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_packet_2eproto::offsets,
    file_level_metadata_packet_2eproto, file_level_enum_descriptors_packet_2eproto,
    file_level_service_descriptors_packet_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_packet_2eproto_getter() {
  return &descriptor_table_packet_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_packet_2eproto(&descriptor_table_packet_2eproto);
namespace wuk {
namespace im {
namespace base {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RequestType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_packet_2eproto);
  return file_level_enum_descriptors_packet_2eproto[0];
}
bool RequestType_IsValid(int value) {
  switch (value) {
    case 0:
    case 10:
    case 11:
    case 12:
    case 20:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class BaseRequest::_Internal {
 public:
};

BaseRequest::BaseRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:wuk.im.base.BaseRequest)
}
BaseRequest::BaseRequest(const BaseRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BaseRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.m_type_){}
    , decltype(_impl_.m_id_){}
    , decltype(_impl_.m_sequence_){}
    , decltype(_impl_.m_segment_){}
    , decltype(_impl_.m_timestamp_){}
    , decltype(_impl_.m_proto_ver_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.m_type_, &from._impl_.m_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.m_proto_ver_) -
    reinterpret_cast<char*>(&_impl_.m_type_)) + sizeof(_impl_.m_proto_ver_));
  // @@protoc_insertion_point(copy_constructor:wuk.im.base.BaseRequest)
}

inline void BaseRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.m_type_){0}
    , decltype(_impl_.m_id_){0u}
    , decltype(_impl_.m_sequence_){0u}
    , decltype(_impl_.m_segment_){0u}
    , decltype(_impl_.m_timestamp_){uint64_t{0u}}
    , decltype(_impl_.m_proto_ver_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BaseRequest::~BaseRequest() {
  // @@protoc_insertion_point(destructor:wuk.im.base.BaseRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BaseRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BaseRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BaseRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:wuk.im.base.BaseRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.m_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.m_proto_ver_) -
      reinterpret_cast<char*>(&_impl_.m_type_)) + sizeof(_impl_.m_proto_ver_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BaseRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .wuk.im.base.RequestType m_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_m_type(static_cast<::wuk::im::base::RequestType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint32 m_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.m_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 m_sequence = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.m_sequence_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 m_segment = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.m_segment_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 m_proto_ver = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.m_proto_ver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 m_timestamp = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.m_timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BaseRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:wuk.im.base.BaseRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .wuk.im.base.RequestType m_type = 1;
  if (this->_internal_m_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_m_type(), target);
  }

  // uint32 m_id = 2;
  if (this->_internal_m_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_m_id(), target);
  }

  // uint32 m_sequence = 3;
  if (this->_internal_m_sequence() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_m_sequence(), target);
  }

  // uint32 m_segment = 4;
  if (this->_internal_m_segment() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_m_segment(), target);
  }

  // uint32 m_proto_ver = 5;
  if (this->_internal_m_proto_ver() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_m_proto_ver(), target);
  }

  // uint64 m_timestamp = 6;
  if (this->_internal_m_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_m_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:wuk.im.base.BaseRequest)
  return target;
}

size_t BaseRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wuk.im.base.BaseRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .wuk.im.base.RequestType m_type = 1;
  if (this->_internal_m_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_m_type());
  }

  // uint32 m_id = 2;
  if (this->_internal_m_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_m_id());
  }

  // uint32 m_sequence = 3;
  if (this->_internal_m_sequence() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_m_sequence());
  }

  // uint32 m_segment = 4;
  if (this->_internal_m_segment() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_m_segment());
  }

  // uint64 m_timestamp = 6;
  if (this->_internal_m_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_m_timestamp());
  }

  // uint32 m_proto_ver = 5;
  if (this->_internal_m_proto_ver() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_m_proto_ver());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BaseRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BaseRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BaseRequest::GetClassData() const { return &_class_data_; }


void BaseRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BaseRequest*>(&to_msg);
  auto& from = static_cast<const BaseRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wuk.im.base.BaseRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_m_type() != 0) {
    _this->_internal_set_m_type(from._internal_m_type());
  }
  if (from._internal_m_id() != 0) {
    _this->_internal_set_m_id(from._internal_m_id());
  }
  if (from._internal_m_sequence() != 0) {
    _this->_internal_set_m_sequence(from._internal_m_sequence());
  }
  if (from._internal_m_segment() != 0) {
    _this->_internal_set_m_segment(from._internal_m_segment());
  }
  if (from._internal_m_timestamp() != 0) {
    _this->_internal_set_m_timestamp(from._internal_m_timestamp());
  }
  if (from._internal_m_proto_ver() != 0) {
    _this->_internal_set_m_proto_ver(from._internal_m_proto_ver());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BaseRequest::CopyFrom(const BaseRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wuk.im.base.BaseRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BaseRequest::IsInitialized() const {
  return true;
}

void BaseRequest::InternalSwap(BaseRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BaseRequest, _impl_.m_proto_ver_)
      + sizeof(BaseRequest::_impl_.m_proto_ver_)
      - PROTOBUF_FIELD_OFFSET(BaseRequest, _impl_.m_type_)>(
          reinterpret_cast<char*>(&_impl_.m_type_),
          reinterpret_cast<char*>(&other->_impl_.m_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BaseRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_packet_2eproto_getter, &descriptor_table_packet_2eproto_once,
      file_level_metadata_packet_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace base
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::wuk::im::base::BaseRequest*
Arena::CreateMaybeMessage< ::wuk::im::base::BaseRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::wuk::im::base::BaseRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
