// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WukPacket.proto

#include "net/WukPacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace wuk {
namespace net {
PROTOBUF_CONSTEXPR Message::Message(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.m_content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_type_)*/0
  , /*decltype(_impl_.m_sequence_)*/0u
  , /*decltype(_impl_.m_segment_id_)*/0u
  , /*decltype(_impl_.m_proto_ver_)*/0u
  , /*decltype(_impl_.m_sender_)*/uint64_t{0u}
  , /*decltype(_impl_.m_recipient_)*/uint64_t{0u}
  , /*decltype(_impl_.m_timestamp_)*/0
  , /*decltype(_impl_.m_length_)*/0u
  , /*decltype(_impl_.m_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageDefaultTypeInternal() {}
  union {
    Message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace net
}  // namespace wuk
static ::_pb::Metadata file_level_metadata_WukPacket_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_WukPacket_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_WukPacket_2eproto = nullptr;

const uint32_t TableStruct_WukPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_type_),
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_sequence_),
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_segment_id_),
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_proto_ver_),
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_sender_),
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_recipient_),
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_timestamp_),
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_length_),
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_id_),
  PROTOBUF_FIELD_OFFSET(::wuk::net::Message, _impl_.m_content_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::wuk::net::Message)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::wuk::net::_Message_default_instance_._instance,
};

const char descriptor_table_protodef_WukPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017WukPacket.proto\022\007wuk.net\"\335\001\n\007Message\022$"
  "\n\006m_type\030\001 \001(\0162\024.wuk.net.MessageType\022\022\n\n"
  "m_sequence\030\002 \001(\r\022\024\n\014m_segment_id\030\003 \001(\r\022\023"
  "\n\013m_proto_ver\030\004 \001(\r\022\020\n\010m_sender\030\005 \001(\004\022\023\n"
  "\013m_recipient\030\006 \001(\004\022\023\n\013m_timestamp\030\007 \001(\001\022"
  "\020\n\010m_length\030\010 \001(\r\022\014\n\004m_id\030\t \001(\r\022\021\n\tm_con"
  "tent\030\n \001(\014*\266\001\n\013MessageType\022\010\n\004NONE\020\000\022\010\n\004"
  "FILE\020\001\022\010\n\004DATA\020\002\022\013\n\007SEGMENT\020\004\022\010\n\004OVER\020\010\022"
  "\n\n\006XCRYPT\020\020\022\013\n\007MESSAGE\020 \022\n\n\006URGENT\020@\022\n\n\005"
  "IMAGE\020\200\001\022\n\n\005VIDEO\020\200\002\022\n\n\005AUDIO\020\200\004\022\t\n\004ANYM"
  "\020\200\010\022\r\n\005GROUP\020\200\200\200\200\004\022\017\n\007PRIVACY\020\200\200\200\200\002b\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_WukPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_WukPacket_2eproto = {
    false, false, 443, descriptor_table_protodef_WukPacket_2eproto,
    "WukPacket.proto",
    &descriptor_table_WukPacket_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_WukPacket_2eproto::offsets,
    file_level_metadata_WukPacket_2eproto, file_level_enum_descriptors_WukPacket_2eproto,
    file_level_service_descriptors_WukPacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_WukPacket_2eproto_getter() {
  return &descriptor_table_WukPacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_WukPacket_2eproto(&descriptor_table_WukPacket_2eproto);
namespace wuk {
namespace net {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_WukPacket_2eproto);
  return file_level_enum_descriptors_WukPacket_2eproto[0];
}
bool MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 16:
    case 32:
    case 64:
    case 128:
    case 256:
    case 512:
    case 1024:
    case 536870912:
    case 1073741824:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Message::_Internal {
 public:
};

Message::Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:wuk.net.Message)
}
Message::Message(const Message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Message* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.m_content_){}
    , decltype(_impl_.m_type_){}
    , decltype(_impl_.m_sequence_){}
    , decltype(_impl_.m_segment_id_){}
    , decltype(_impl_.m_proto_ver_){}
    , decltype(_impl_.m_sender_){}
    , decltype(_impl_.m_recipient_){}
    , decltype(_impl_.m_timestamp_){}
    , decltype(_impl_.m_length_){}
    , decltype(_impl_.m_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.m_content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_content().empty()) {
    _this->_impl_.m_content_.Set(from._internal_m_content(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.m_type_, &from._impl_.m_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.m_id_) -
    reinterpret_cast<char*>(&_impl_.m_type_)) + sizeof(_impl_.m_id_));
  // @@protoc_insertion_point(copy_constructor:wuk.net.Message)
}

inline void Message::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.m_content_){}
    , decltype(_impl_.m_type_){0}
    , decltype(_impl_.m_sequence_){0u}
    , decltype(_impl_.m_segment_id_){0u}
    , decltype(_impl_.m_proto_ver_){0u}
    , decltype(_impl_.m_sender_){uint64_t{0u}}
    , decltype(_impl_.m_recipient_){uint64_t{0u}}
    , decltype(_impl_.m_timestamp_){0}
    , decltype(_impl_.m_length_){0u}
    , decltype(_impl_.m_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.m_content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:wuk.net.Message)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.m_content_.Destroy();
}

void Message::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:wuk.net.Message)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.m_content_.ClearToEmpty();
  ::memset(&_impl_.m_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.m_id_) -
      reinterpret_cast<char*>(&_impl_.m_type_)) + sizeof(_impl_.m_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Message::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .wuk.net.MessageType m_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_m_type(static_cast<::wuk::net::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint32 m_sequence = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.m_sequence_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 m_segment_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.m_segment_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 m_proto_ver = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.m_proto_ver_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 m_sender = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.m_sender_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 m_recipient = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.m_recipient_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double m_timestamp = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.m_timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // uint32 m_length = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.m_length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 m_id = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.m_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes m_content = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_m_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Message::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:wuk.net.Message)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .wuk.net.MessageType m_type = 1;
  if (this->_internal_m_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_m_type(), target);
  }

  // uint32 m_sequence = 2;
  if (this->_internal_m_sequence() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_m_sequence(), target);
  }

  // uint32 m_segment_id = 3;
  if (this->_internal_m_segment_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_m_segment_id(), target);
  }

  // uint32 m_proto_ver = 4;
  if (this->_internal_m_proto_ver() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_m_proto_ver(), target);
  }

  // uint64 m_sender = 5;
  if (this->_internal_m_sender() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_m_sender(), target);
  }

  // uint64 m_recipient = 6;
  if (this->_internal_m_recipient() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_m_recipient(), target);
  }

  // double m_timestamp = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_timestamp = this->_internal_m_timestamp();
  uint64_t raw_m_timestamp;
  memcpy(&raw_m_timestamp, &tmp_m_timestamp, sizeof(tmp_m_timestamp));
  if (raw_m_timestamp != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_m_timestamp(), target);
  }

  // uint32 m_length = 8;
  if (this->_internal_m_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(8, this->_internal_m_length(), target);
  }

  // uint32 m_id = 9;
  if (this->_internal_m_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(9, this->_internal_m_id(), target);
  }

  // bytes m_content = 10;
  if (!this->_internal_m_content().empty()) {
    target = stream->WriteBytesMaybeAliased(
        10, this->_internal_m_content(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:wuk.net.Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wuk.net.Message)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes m_content = 10;
  if (!this->_internal_m_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_m_content());
  }

  // .wuk.net.MessageType m_type = 1;
  if (this->_internal_m_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_m_type());
  }

  // uint32 m_sequence = 2;
  if (this->_internal_m_sequence() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_m_sequence());
  }

  // uint32 m_segment_id = 3;
  if (this->_internal_m_segment_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_m_segment_id());
  }

  // uint32 m_proto_ver = 4;
  if (this->_internal_m_proto_ver() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_m_proto_ver());
  }

  // uint64 m_sender = 5;
  if (this->_internal_m_sender() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_m_sender());
  }

  // uint64 m_recipient = 6;
  if (this->_internal_m_recipient() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_m_recipient());
  }

  // double m_timestamp = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_timestamp = this->_internal_m_timestamp();
  uint64_t raw_m_timestamp;
  memcpy(&raw_m_timestamp, &tmp_m_timestamp, sizeof(tmp_m_timestamp));
  if (raw_m_timestamp != 0) {
    total_size += 1 + 8;
  }

  // uint32 m_length = 8;
  if (this->_internal_m_length() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_m_length());
  }

  // uint32 m_id = 9;
  if (this->_internal_m_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_m_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Message::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Message::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Message::GetClassData() const { return &_class_data_; }


void Message::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Message*>(&to_msg);
  auto& from = static_cast<const Message&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wuk.net.Message)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_m_content().empty()) {
    _this->_internal_set_m_content(from._internal_m_content());
  }
  if (from._internal_m_type() != 0) {
    _this->_internal_set_m_type(from._internal_m_type());
  }
  if (from._internal_m_sequence() != 0) {
    _this->_internal_set_m_sequence(from._internal_m_sequence());
  }
  if (from._internal_m_segment_id() != 0) {
    _this->_internal_set_m_segment_id(from._internal_m_segment_id());
  }
  if (from._internal_m_proto_ver() != 0) {
    _this->_internal_set_m_proto_ver(from._internal_m_proto_ver());
  }
  if (from._internal_m_sender() != 0) {
    _this->_internal_set_m_sender(from._internal_m_sender());
  }
  if (from._internal_m_recipient() != 0) {
    _this->_internal_set_m_recipient(from._internal_m_recipient());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_timestamp = from._internal_m_timestamp();
  uint64_t raw_m_timestamp;
  memcpy(&raw_m_timestamp, &tmp_m_timestamp, sizeof(tmp_m_timestamp));
  if (raw_m_timestamp != 0) {
    _this->_internal_set_m_timestamp(from._internal_m_timestamp());
  }
  if (from._internal_m_length() != 0) {
    _this->_internal_set_m_length(from._internal_m_length());
  }
  if (from._internal_m_id() != 0) {
    _this->_internal_set_m_id(from._internal_m_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wuk.net.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::InternalSwap(Message* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_content_, lhs_arena,
      &other->_impl_.m_content_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Message, _impl_.m_id_)
      + sizeof(Message::_impl_.m_id_)
      - PROTOBUF_FIELD_OFFSET(Message, _impl_.m_type_)>(
          reinterpret_cast<char*>(&_impl_.m_type_),
          reinterpret_cast<char*>(&other->_impl_.m_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_WukPacket_2eproto_getter, &descriptor_table_WukPacket_2eproto_once,
      file_level_metadata_WukPacket_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace net
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::wuk::net::Message*
Arena::CreateMaybeMessage< ::wuk::net::Message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::wuk::net::Message >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
