// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WukPacket.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_WukPacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_WukPacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_WukPacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_WukPacket_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_WukPacket_2eproto;
namespace wuk {
namespace net {
class Message;
struct MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace net
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> ::wuk::net::Message* Arena::CreateMaybeMessage<::wuk::net::Message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wuk {
namespace net {

enum MessageType : int {
  NONE = 0,
  FILE = 1,
  DATA = 2,
  SEGMENT = 4,
  OVER = 8,
  XCRYPT = 16,
  MESSAGE = 32,
  URGENT = 64,
  IMAGE = 128,
  VIDEO = 256,
  AUDIO = 512,
  ANYM = 1024,
  GROUP = 1073741824,
  PRIVACY = 536870912,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = NONE;
constexpr MessageType MessageType_MAX = GROUP;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class Message final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wuk.net.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() override;
  explicit PROTOBUF_CONSTEXPR Message(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Message& default_instance() {
    return *internal_default_instance();
  }
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Message& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Message& from) {
    Message::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wuk.net.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMContentFieldNumber = 10,
    kMTypeFieldNumber = 1,
    kMSequenceFieldNumber = 2,
    kMSegmentIdFieldNumber = 3,
    kMProtoVerFieldNumber = 4,
    kMSenderFieldNumber = 5,
    kMRecipientFieldNumber = 6,
    kMTimestampFieldNumber = 7,
    kMLengthFieldNumber = 8,
    kMIdFieldNumber = 9,
  };
  // bytes m_content = 10;
  void clear_m_content();
  const std::string& m_content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_content();
  PROTOBUF_NODISCARD std::string* release_m_content();
  void set_allocated_m_content(std::string* m_content);
  private:
  const std::string& _internal_m_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_content(const std::string& value);
  std::string* _internal_mutable_m_content();
  public:

  // .wuk.net.MessageType m_type = 1;
  void clear_m_type();
  ::wuk::net::MessageType m_type() const;
  void set_m_type(::wuk::net::MessageType value);
  private:
  ::wuk::net::MessageType _internal_m_type() const;
  void _internal_set_m_type(::wuk::net::MessageType value);
  public:

  // uint32 m_sequence = 2;
  void clear_m_sequence();
  uint32_t m_sequence() const;
  void set_m_sequence(uint32_t value);
  private:
  uint32_t _internal_m_sequence() const;
  void _internal_set_m_sequence(uint32_t value);
  public:

  // uint32 m_segment_id = 3;
  void clear_m_segment_id();
  uint32_t m_segment_id() const;
  void set_m_segment_id(uint32_t value);
  private:
  uint32_t _internal_m_segment_id() const;
  void _internal_set_m_segment_id(uint32_t value);
  public:

  // uint32 m_proto_ver = 4;
  void clear_m_proto_ver();
  uint32_t m_proto_ver() const;
  void set_m_proto_ver(uint32_t value);
  private:
  uint32_t _internal_m_proto_ver() const;
  void _internal_set_m_proto_ver(uint32_t value);
  public:

  // uint64 m_sender = 5;
  void clear_m_sender();
  uint64_t m_sender() const;
  void set_m_sender(uint64_t value);
  private:
  uint64_t _internal_m_sender() const;
  void _internal_set_m_sender(uint64_t value);
  public:

  // uint64 m_recipient = 6;
  void clear_m_recipient();
  uint64_t m_recipient() const;
  void set_m_recipient(uint64_t value);
  private:
  uint64_t _internal_m_recipient() const;
  void _internal_set_m_recipient(uint64_t value);
  public:

  // double m_timestamp = 7;
  void clear_m_timestamp();
  double m_timestamp() const;
  void set_m_timestamp(double value);
  private:
  double _internal_m_timestamp() const;
  void _internal_set_m_timestamp(double value);
  public:

  // uint32 m_length = 8;
  void clear_m_length();
  uint32_t m_length() const;
  void set_m_length(uint32_t value);
  private:
  uint32_t _internal_m_length() const;
  void _internal_set_m_length(uint32_t value);
  public:

  // uint32 m_id = 9;
  void clear_m_id();
  uint32_t m_id() const;
  void set_m_id(uint32_t value);
  private:
  uint32_t _internal_m_id() const;
  void _internal_set_m_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:wuk.net.Message)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_content_;
    int m_type_;
    uint32_t m_sequence_;
    uint32_t m_segment_id_;
    uint32_t m_proto_ver_;
    uint64_t m_sender_;
    uint64_t m_recipient_;
    double m_timestamp_;
    uint32_t m_length_;
    uint32_t m_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WukPacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Message

// .wuk.net.MessageType m_type = 1;
inline void Message::clear_m_type() {
  _impl_.m_type_ = 0;
}
inline ::wuk::net::MessageType Message::_internal_m_type() const {
  return static_cast< ::wuk::net::MessageType >(_impl_.m_type_);
}
inline ::wuk::net::MessageType Message::m_type() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_type)
  return _internal_m_type();
}
inline void Message::_internal_set_m_type(::wuk::net::MessageType value) {
  
  _impl_.m_type_ = value;
}
inline void Message::set_m_type(::wuk::net::MessageType value) {
  _internal_set_m_type(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_type)
}

// uint32 m_sequence = 2;
inline void Message::clear_m_sequence() {
  _impl_.m_sequence_ = 0u;
}
inline uint32_t Message::_internal_m_sequence() const {
  return _impl_.m_sequence_;
}
inline uint32_t Message::m_sequence() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_sequence)
  return _internal_m_sequence();
}
inline void Message::_internal_set_m_sequence(uint32_t value) {
  
  _impl_.m_sequence_ = value;
}
inline void Message::set_m_sequence(uint32_t value) {
  _internal_set_m_sequence(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_sequence)
}

// uint32 m_segment_id = 3;
inline void Message::clear_m_segment_id() {
  _impl_.m_segment_id_ = 0u;
}
inline uint32_t Message::_internal_m_segment_id() const {
  return _impl_.m_segment_id_;
}
inline uint32_t Message::m_segment_id() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_segment_id)
  return _internal_m_segment_id();
}
inline void Message::_internal_set_m_segment_id(uint32_t value) {
  
  _impl_.m_segment_id_ = value;
}
inline void Message::set_m_segment_id(uint32_t value) {
  _internal_set_m_segment_id(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_segment_id)
}

// uint32 m_proto_ver = 4;
inline void Message::clear_m_proto_ver() {
  _impl_.m_proto_ver_ = 0u;
}
inline uint32_t Message::_internal_m_proto_ver() const {
  return _impl_.m_proto_ver_;
}
inline uint32_t Message::m_proto_ver() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_proto_ver)
  return _internal_m_proto_ver();
}
inline void Message::_internal_set_m_proto_ver(uint32_t value) {
  
  _impl_.m_proto_ver_ = value;
}
inline void Message::set_m_proto_ver(uint32_t value) {
  _internal_set_m_proto_ver(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_proto_ver)
}

// uint64 m_sender = 5;
inline void Message::clear_m_sender() {
  _impl_.m_sender_ = uint64_t{0u};
}
inline uint64_t Message::_internal_m_sender() const {
  return _impl_.m_sender_;
}
inline uint64_t Message::m_sender() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_sender)
  return _internal_m_sender();
}
inline void Message::_internal_set_m_sender(uint64_t value) {
  
  _impl_.m_sender_ = value;
}
inline void Message::set_m_sender(uint64_t value) {
  _internal_set_m_sender(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_sender)
}

// uint64 m_recipient = 6;
inline void Message::clear_m_recipient() {
  _impl_.m_recipient_ = uint64_t{0u};
}
inline uint64_t Message::_internal_m_recipient() const {
  return _impl_.m_recipient_;
}
inline uint64_t Message::m_recipient() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_recipient)
  return _internal_m_recipient();
}
inline void Message::_internal_set_m_recipient(uint64_t value) {
  
  _impl_.m_recipient_ = value;
}
inline void Message::set_m_recipient(uint64_t value) {
  _internal_set_m_recipient(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_recipient)
}

// double m_timestamp = 7;
inline void Message::clear_m_timestamp() {
  _impl_.m_timestamp_ = 0;
}
inline double Message::_internal_m_timestamp() const {
  return _impl_.m_timestamp_;
}
inline double Message::m_timestamp() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_timestamp)
  return _internal_m_timestamp();
}
inline void Message::_internal_set_m_timestamp(double value) {
  
  _impl_.m_timestamp_ = value;
}
inline void Message::set_m_timestamp(double value) {
  _internal_set_m_timestamp(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_timestamp)
}

// uint32 m_length = 8;
inline void Message::clear_m_length() {
  _impl_.m_length_ = 0u;
}
inline uint32_t Message::_internal_m_length() const {
  return _impl_.m_length_;
}
inline uint32_t Message::m_length() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_length)
  return _internal_m_length();
}
inline void Message::_internal_set_m_length(uint32_t value) {
  
  _impl_.m_length_ = value;
}
inline void Message::set_m_length(uint32_t value) {
  _internal_set_m_length(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_length)
}

// uint32 m_id = 9;
inline void Message::clear_m_id() {
  _impl_.m_id_ = 0u;
}
inline uint32_t Message::_internal_m_id() const {
  return _impl_.m_id_;
}
inline uint32_t Message::m_id() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_id)
  return _internal_m_id();
}
inline void Message::_internal_set_m_id(uint32_t value) {
  
  _impl_.m_id_ = value;
}
inline void Message::set_m_id(uint32_t value) {
  _internal_set_m_id(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_id)
}

// bytes m_content = 10;
inline void Message::clear_m_content() {
  _impl_.m_content_.ClearToEmpty();
}
inline const std::string& Message::m_content() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.m_content)
  return _internal_m_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_m_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_content_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.net.Message.m_content)
}
inline std::string* Message::mutable_m_content() {
  std::string* _s = _internal_mutable_m_content();
  // @@protoc_insertion_point(field_mutable:wuk.net.Message.m_content)
  return _s;
}
inline const std::string& Message::_internal_m_content() const {
  return _impl_.m_content_.Get();
}
inline void Message::_internal_set_m_content(const std::string& value) {
  
  _impl_.m_content_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_m_content() {
  
  return _impl_.m_content_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_m_content() {
  // @@protoc_insertion_point(field_release:wuk.net.Message.m_content)
  return _impl_.m_content_.Release();
}
inline void Message::set_allocated_m_content(std::string* m_content) {
  if (m_content != nullptr) {
    
  } else {
    
  }
  _impl_.m_content_.SetAllocated(m_content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_content_.IsDefault()) {
    _impl_.m_content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.net.Message.m_content)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace net
}  // namespace wuk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::wuk::net::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::wuk::net::MessageType>() {
  return ::wuk::net::MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_WukPacket_2eproto
