// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WukPacket.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_WukPacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_WukPacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_WukPacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_WukPacket_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_WukPacket_2eproto;
namespace wuk {
namespace net {
class Message;
struct MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace net
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> ::wuk::net::Message* Arena::CreateMaybeMessage<::wuk::net::Message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wuk {
namespace net {

enum MessageType : int {
  NONE = 0,
  FILE = 1,
  DATA = 2,
  SEGMENT = 4,
  OVER = 8,
  XCRYPT = 16,
  MESSAGE = 32,
  URGENT = 64,
  IMAGE = 128,
  VIDEO = 256,
  AUDIO = 512,
  ANYM = 1024,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = NONE;
constexpr MessageType MessageType_MAX = ANYM;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class Message final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wuk.net.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() override;
  explicit PROTOBUF_CONSTEXPR Message(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Message& default_instance() {
    return *internal_default_instance();
  }
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Message& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Message& from) {
    Message::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wuk.net.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 10,
    kMsgTypeFieldNumber = 1,
    kMsgSeqFieldNumber = 2,
    kSegIdFieldNumber = 3,
    kProtoVerFieldNumber = 4,
    kSenderIdFieldNumber = 5,
    kRecipientIdFieldNumber = 6,
    kTimeStampFieldNumber = 7,
    kMsgSizeFieldNumber = 8,
    kMsgIdFieldNumber = 9,
  };
  // bytes message = 10;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .wuk.net.MessageType msg_type = 1;
  void clear_msg_type();
  ::wuk::net::MessageType msg_type() const;
  void set_msg_type(::wuk::net::MessageType value);
  private:
  ::wuk::net::MessageType _internal_msg_type() const;
  void _internal_set_msg_type(::wuk::net::MessageType value);
  public:

  // uint32 msg_seq = 2;
  void clear_msg_seq();
  uint32_t msg_seq() const;
  void set_msg_seq(uint32_t value);
  private:
  uint32_t _internal_msg_seq() const;
  void _internal_set_msg_seq(uint32_t value);
  public:

  // uint32 seg_id = 3;
  void clear_seg_id();
  uint32_t seg_id() const;
  void set_seg_id(uint32_t value);
  private:
  uint32_t _internal_seg_id() const;
  void _internal_set_seg_id(uint32_t value);
  public:

  // uint32 proto_ver = 4;
  void clear_proto_ver();
  uint32_t proto_ver() const;
  void set_proto_ver(uint32_t value);
  private:
  uint32_t _internal_proto_ver() const;
  void _internal_set_proto_ver(uint32_t value);
  public:

  // uint64 sender_id = 5;
  void clear_sender_id();
  uint64_t sender_id() const;
  void set_sender_id(uint64_t value);
  private:
  uint64_t _internal_sender_id() const;
  void _internal_set_sender_id(uint64_t value);
  public:

  // uint64 recipient_id = 6;
  void clear_recipient_id();
  uint64_t recipient_id() const;
  void set_recipient_id(uint64_t value);
  private:
  uint64_t _internal_recipient_id() const;
  void _internal_set_recipient_id(uint64_t value);
  public:

  // double time_stamp = 7;
  void clear_time_stamp();
  double time_stamp() const;
  void set_time_stamp(double value);
  private:
  double _internal_time_stamp() const;
  void _internal_set_time_stamp(double value);
  public:

  // uint32 msg_size = 8;
  void clear_msg_size();
  uint32_t msg_size() const;
  void set_msg_size(uint32_t value);
  private:
  uint32_t _internal_msg_size() const;
  void _internal_set_msg_size(uint32_t value);
  public:

  // uint32 msg_id = 9;
  void clear_msg_id();
  uint32_t msg_id() const;
  void set_msg_id(uint32_t value);
  private:
  uint32_t _internal_msg_id() const;
  void _internal_set_msg_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:wuk.net.Message)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    int msg_type_;
    uint32_t msg_seq_;
    uint32_t seg_id_;
    uint32_t proto_ver_;
    uint64_t sender_id_;
    uint64_t recipient_id_;
    double time_stamp_;
    uint32_t msg_size_;
    uint32_t msg_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WukPacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Message

// .wuk.net.MessageType msg_type = 1;
inline void Message::clear_msg_type() {
  _impl_.msg_type_ = 0;
}
inline ::wuk::net::MessageType Message::_internal_msg_type() const {
  return static_cast< ::wuk::net::MessageType >(_impl_.msg_type_);
}
inline ::wuk::net::MessageType Message::msg_type() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.msg_type)
  return _internal_msg_type();
}
inline void Message::_internal_set_msg_type(::wuk::net::MessageType value) {
  
  _impl_.msg_type_ = value;
}
inline void Message::set_msg_type(::wuk::net::MessageType value) {
  _internal_set_msg_type(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.msg_type)
}

// uint32 msg_seq = 2;
inline void Message::clear_msg_seq() {
  _impl_.msg_seq_ = 0u;
}
inline uint32_t Message::_internal_msg_seq() const {
  return _impl_.msg_seq_;
}
inline uint32_t Message::msg_seq() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.msg_seq)
  return _internal_msg_seq();
}
inline void Message::_internal_set_msg_seq(uint32_t value) {
  
  _impl_.msg_seq_ = value;
}
inline void Message::set_msg_seq(uint32_t value) {
  _internal_set_msg_seq(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.msg_seq)
}

// uint32 seg_id = 3;
inline void Message::clear_seg_id() {
  _impl_.seg_id_ = 0u;
}
inline uint32_t Message::_internal_seg_id() const {
  return _impl_.seg_id_;
}
inline uint32_t Message::seg_id() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.seg_id)
  return _internal_seg_id();
}
inline void Message::_internal_set_seg_id(uint32_t value) {
  
  _impl_.seg_id_ = value;
}
inline void Message::set_seg_id(uint32_t value) {
  _internal_set_seg_id(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.seg_id)
}

// uint32 proto_ver = 4;
inline void Message::clear_proto_ver() {
  _impl_.proto_ver_ = 0u;
}
inline uint32_t Message::_internal_proto_ver() const {
  return _impl_.proto_ver_;
}
inline uint32_t Message::proto_ver() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.proto_ver)
  return _internal_proto_ver();
}
inline void Message::_internal_set_proto_ver(uint32_t value) {
  
  _impl_.proto_ver_ = value;
}
inline void Message::set_proto_ver(uint32_t value) {
  _internal_set_proto_ver(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.proto_ver)
}

// uint64 sender_id = 5;
inline void Message::clear_sender_id() {
  _impl_.sender_id_ = uint64_t{0u};
}
inline uint64_t Message::_internal_sender_id() const {
  return _impl_.sender_id_;
}
inline uint64_t Message::sender_id() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.sender_id)
  return _internal_sender_id();
}
inline void Message::_internal_set_sender_id(uint64_t value) {
  
  _impl_.sender_id_ = value;
}
inline void Message::set_sender_id(uint64_t value) {
  _internal_set_sender_id(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.sender_id)
}

// uint64 recipient_id = 6;
inline void Message::clear_recipient_id() {
  _impl_.recipient_id_ = uint64_t{0u};
}
inline uint64_t Message::_internal_recipient_id() const {
  return _impl_.recipient_id_;
}
inline uint64_t Message::recipient_id() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.recipient_id)
  return _internal_recipient_id();
}
inline void Message::_internal_set_recipient_id(uint64_t value) {
  
  _impl_.recipient_id_ = value;
}
inline void Message::set_recipient_id(uint64_t value) {
  _internal_set_recipient_id(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.recipient_id)
}

// double time_stamp = 7;
inline void Message::clear_time_stamp() {
  _impl_.time_stamp_ = 0;
}
inline double Message::_internal_time_stamp() const {
  return _impl_.time_stamp_;
}
inline double Message::time_stamp() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.time_stamp)
  return _internal_time_stamp();
}
inline void Message::_internal_set_time_stamp(double value) {
  
  _impl_.time_stamp_ = value;
}
inline void Message::set_time_stamp(double value) {
  _internal_set_time_stamp(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.time_stamp)
}

// uint32 msg_size = 8;
inline void Message::clear_msg_size() {
  _impl_.msg_size_ = 0u;
}
inline uint32_t Message::_internal_msg_size() const {
  return _impl_.msg_size_;
}
inline uint32_t Message::msg_size() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.msg_size)
  return _internal_msg_size();
}
inline void Message::_internal_set_msg_size(uint32_t value) {
  
  _impl_.msg_size_ = value;
}
inline void Message::set_msg_size(uint32_t value) {
  _internal_set_msg_size(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.msg_size)
}

// uint32 msg_id = 9;
inline void Message::clear_msg_id() {
  _impl_.msg_id_ = 0u;
}
inline uint32_t Message::_internal_msg_id() const {
  return _impl_.msg_id_;
}
inline uint32_t Message::msg_id() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.msg_id)
  return _internal_msg_id();
}
inline void Message::_internal_set_msg_id(uint32_t value) {
  
  _impl_.msg_id_ = value;
}
inline void Message::set_msg_id(uint32_t value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:wuk.net.Message.msg_id)
}

// bytes message = 10;
inline void Message::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& Message::message() const {
  // @@protoc_insertion_point(field_get:wuk.net.Message.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.net.Message.message)
}
inline std::string* Message::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:wuk.net.Message.message)
  return _s;
}
inline const std::string& Message::_internal_message() const {
  return _impl_.message_.Get();
}
inline void Message::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_message() {
  // @@protoc_insertion_point(field_release:wuk.net.Message.message)
  return _impl_.message_.Release();
}
inline void Message::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.net.Message.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace net
}  // namespace wuk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::wuk::net::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::wuk::net::MessageType>() {
  return ::wuk::net::MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_WukPacket_2eproto
