// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WukAccount.proto

#include "WukAccount.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace wuk {
namespace im {
PROTOBUF_CONSTEXPR Message::Message(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.m_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_salt_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_hash_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.m_uid_)*/int64_t{0}
  , /*decltype(_impl_.m_created_)*/0
  , /*decltype(_impl_.m_modified_)*/0
  , /*decltype(_impl_.m_accessed_)*/0
  , /*decltype(_impl_.m_deleted_)*/0
  , /*decltype(_impl_.m_status_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageDefaultTypeInternal() {}
  union {
    Message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace im
}  // namespace wuk
static ::_pb::Metadata file_level_metadata_WukAccount_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_WukAccount_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_WukAccount_2eproto = nullptr;

const uint32_t TableStruct_WukAccount_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _impl_.m_uid_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _impl_.m_name_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _impl_.m_salt_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _impl_.m_hash_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _impl_.m_status_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _impl_.m_created_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _impl_.m_modified_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _impl_.m_accessed_),
  PROTOBUF_FIELD_OFFSET(::wuk::im::Message, _impl_.m_deleted_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::wuk::im::Message)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::wuk::im::_Message_default_instance_._instance,
};

const char descriptor_table_protodef_WukAccount_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020WukAccount.proto\022\006wuk.im\"\300\001\n\007Message\022\r"
  "\n\005m_uid\030\001 \001(\003\022\016\n\006m_name\030\002 \001(\t\022\016\n\006m_salt\030"
  "\003 \001(\014\022\016\n\006m_hash\030\004 \001(\014\022(\n\010m_status\030\005 \001(\0162"
  "\026.wuk.im.ACCOUNT_STATUS\022\021\n\tm_created\030\006 \001"
  "(\001\022\022\n\nm_modified\030\007 \001(\001\022\022\n\nm_accessed\030\010 \001"
  "(\001\022\021\n\tm_deleted\030\t \001(\001*O\n\016ACCOUNT_STATUS\022"
  "\r\n\tUNDEFINED\020\000\022\n\n\006NORMAL\020\001\022\n\n\006BANNED\020\002\022\t"
  "\n\005MUTED\020\003\022\013\n\007DELETED\020\004b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_WukAccount_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_WukAccount_2eproto = {
    false, false, 310, descriptor_table_protodef_WukAccount_2eproto,
    "WukAccount.proto",
    &descriptor_table_WukAccount_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_WukAccount_2eproto::offsets,
    file_level_metadata_WukAccount_2eproto, file_level_enum_descriptors_WukAccount_2eproto,
    file_level_service_descriptors_WukAccount_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_WukAccount_2eproto_getter() {
  return &descriptor_table_WukAccount_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_WukAccount_2eproto(&descriptor_table_WukAccount_2eproto);
namespace wuk {
namespace im {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ACCOUNT_STATUS_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_WukAccount_2eproto);
  return file_level_enum_descriptors_WukAccount_2eproto[0];
}
bool ACCOUNT_STATUS_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Message::_Internal {
 public:
};

Message::Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:wuk.im.Message)
}
Message::Message(const Message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Message* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.m_name_){}
    , decltype(_impl_.m_salt_){}
    , decltype(_impl_.m_hash_){}
    , decltype(_impl_.m_uid_){}
    , decltype(_impl_.m_created_){}
    , decltype(_impl_.m_modified_){}
    , decltype(_impl_.m_accessed_){}
    , decltype(_impl_.m_deleted_){}
    , decltype(_impl_.m_status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.m_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_name().empty()) {
    _this->_impl_.m_name_.Set(from._internal_m_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.m_salt_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_salt_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_salt().empty()) {
    _this->_impl_.m_salt_.Set(from._internal_m_salt(), 
      _this->GetArenaForAllocation());
  }
  _impl_.m_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_m_hash().empty()) {
    _this->_impl_.m_hash_.Set(from._internal_m_hash(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.m_uid_, &from._impl_.m_uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.m_status_) -
    reinterpret_cast<char*>(&_impl_.m_uid_)) + sizeof(_impl_.m_status_));
  // @@protoc_insertion_point(copy_constructor:wuk.im.Message)
}

inline void Message::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.m_name_){}
    , decltype(_impl_.m_salt_){}
    , decltype(_impl_.m_hash_){}
    , decltype(_impl_.m_uid_){int64_t{0}}
    , decltype(_impl_.m_created_){0}
    , decltype(_impl_.m_modified_){0}
    , decltype(_impl_.m_accessed_){0}
    , decltype(_impl_.m_deleted_){0}
    , decltype(_impl_.m_status_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.m_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.m_salt_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_salt_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.m_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.m_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:wuk.im.Message)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.m_name_.Destroy();
  _impl_.m_salt_.Destroy();
  _impl_.m_hash_.Destroy();
}

void Message::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:wuk.im.Message)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.m_name_.ClearToEmpty();
  _impl_.m_salt_.ClearToEmpty();
  _impl_.m_hash_.ClearToEmpty();
  ::memset(&_impl_.m_uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.m_status_) -
      reinterpret_cast<char*>(&_impl_.m_uid_)) + sizeof(_impl_.m_status_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Message::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 m_uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.m_uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string m_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_m_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "wuk.im.Message.m_name"));
        } else
          goto handle_unusual;
        continue;
      // bytes m_salt = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_m_salt();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes m_hash = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_m_hash();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .wuk.im.ACCOUNT_STATUS m_status = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_m_status(static_cast<::wuk::im::ACCOUNT_STATUS>(val));
        } else
          goto handle_unusual;
        continue;
      // double m_created = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.m_created_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m_modified = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.m_modified_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m_accessed = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 65)) {
          _impl_.m_accessed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m_deleted = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 73)) {
          _impl_.m_deleted_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Message::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:wuk.im.Message)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 m_uid = 1;
  if (this->_internal_m_uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_m_uid(), target);
  }

  // string m_name = 2;
  if (!this->_internal_m_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_m_name().data(), static_cast<int>(this->_internal_m_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "wuk.im.Message.m_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_m_name(), target);
  }

  // bytes m_salt = 3;
  if (!this->_internal_m_salt().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_m_salt(), target);
  }

  // bytes m_hash = 4;
  if (!this->_internal_m_hash().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_m_hash(), target);
  }

  // .wuk.im.ACCOUNT_STATUS m_status = 5;
  if (this->_internal_m_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_m_status(), target);
  }

  // double m_created = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_created = this->_internal_m_created();
  uint64_t raw_m_created;
  memcpy(&raw_m_created, &tmp_m_created, sizeof(tmp_m_created));
  if (raw_m_created != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_m_created(), target);
  }

  // double m_modified = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_modified = this->_internal_m_modified();
  uint64_t raw_m_modified;
  memcpy(&raw_m_modified, &tmp_m_modified, sizeof(tmp_m_modified));
  if (raw_m_modified != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_m_modified(), target);
  }

  // double m_accessed = 8;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_accessed = this->_internal_m_accessed();
  uint64_t raw_m_accessed;
  memcpy(&raw_m_accessed, &tmp_m_accessed, sizeof(tmp_m_accessed));
  if (raw_m_accessed != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(8, this->_internal_m_accessed(), target);
  }

  // double m_deleted = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_deleted = this->_internal_m_deleted();
  uint64_t raw_m_deleted;
  memcpy(&raw_m_deleted, &tmp_m_deleted, sizeof(tmp_m_deleted));
  if (raw_m_deleted != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(9, this->_internal_m_deleted(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:wuk.im.Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:wuk.im.Message)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string m_name = 2;
  if (!this->_internal_m_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_m_name());
  }

  // bytes m_salt = 3;
  if (!this->_internal_m_salt().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_m_salt());
  }

  // bytes m_hash = 4;
  if (!this->_internal_m_hash().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_m_hash());
  }

  // int64 m_uid = 1;
  if (this->_internal_m_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_m_uid());
  }

  // double m_created = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_created = this->_internal_m_created();
  uint64_t raw_m_created;
  memcpy(&raw_m_created, &tmp_m_created, sizeof(tmp_m_created));
  if (raw_m_created != 0) {
    total_size += 1 + 8;
  }

  // double m_modified = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_modified = this->_internal_m_modified();
  uint64_t raw_m_modified;
  memcpy(&raw_m_modified, &tmp_m_modified, sizeof(tmp_m_modified));
  if (raw_m_modified != 0) {
    total_size += 1 + 8;
  }

  // double m_accessed = 8;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_accessed = this->_internal_m_accessed();
  uint64_t raw_m_accessed;
  memcpy(&raw_m_accessed, &tmp_m_accessed, sizeof(tmp_m_accessed));
  if (raw_m_accessed != 0) {
    total_size += 1 + 8;
  }

  // double m_deleted = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_deleted = this->_internal_m_deleted();
  uint64_t raw_m_deleted;
  memcpy(&raw_m_deleted, &tmp_m_deleted, sizeof(tmp_m_deleted));
  if (raw_m_deleted != 0) {
    total_size += 1 + 8;
  }

  // .wuk.im.ACCOUNT_STATUS m_status = 5;
  if (this->_internal_m_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_m_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Message::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Message::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Message::GetClassData() const { return &_class_data_; }


void Message::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Message*>(&to_msg);
  auto& from = static_cast<const Message&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wuk.im.Message)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_m_name().empty()) {
    _this->_internal_set_m_name(from._internal_m_name());
  }
  if (!from._internal_m_salt().empty()) {
    _this->_internal_set_m_salt(from._internal_m_salt());
  }
  if (!from._internal_m_hash().empty()) {
    _this->_internal_set_m_hash(from._internal_m_hash());
  }
  if (from._internal_m_uid() != 0) {
    _this->_internal_set_m_uid(from._internal_m_uid());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_created = from._internal_m_created();
  uint64_t raw_m_created;
  memcpy(&raw_m_created, &tmp_m_created, sizeof(tmp_m_created));
  if (raw_m_created != 0) {
    _this->_internal_set_m_created(from._internal_m_created());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_modified = from._internal_m_modified();
  uint64_t raw_m_modified;
  memcpy(&raw_m_modified, &tmp_m_modified, sizeof(tmp_m_modified));
  if (raw_m_modified != 0) {
    _this->_internal_set_m_modified(from._internal_m_modified());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_accessed = from._internal_m_accessed();
  uint64_t raw_m_accessed;
  memcpy(&raw_m_accessed, &tmp_m_accessed, sizeof(tmp_m_accessed));
  if (raw_m_accessed != 0) {
    _this->_internal_set_m_accessed(from._internal_m_accessed());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m_deleted = from._internal_m_deleted();
  uint64_t raw_m_deleted;
  memcpy(&raw_m_deleted, &tmp_m_deleted, sizeof(tmp_m_deleted));
  if (raw_m_deleted != 0) {
    _this->_internal_set_m_deleted(from._internal_m_deleted());
  }
  if (from._internal_m_status() != 0) {
    _this->_internal_set_m_status(from._internal_m_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wuk.im.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::InternalSwap(Message* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_name_, lhs_arena,
      &other->_impl_.m_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_salt_, lhs_arena,
      &other->_impl_.m_salt_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.m_hash_, lhs_arena,
      &other->_impl_.m_hash_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Message, _impl_.m_status_)
      + sizeof(Message::_impl_.m_status_)
      - PROTOBUF_FIELD_OFFSET(Message, _impl_.m_uid_)>(
          reinterpret_cast<char*>(&_impl_.m_uid_),
          reinterpret_cast<char*>(&other->_impl_.m_uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_WukAccount_2eproto_getter, &descriptor_table_WukAccount_2eproto_once,
      file_level_metadata_WukAccount_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::wuk::im::Message*
Arena::CreateMaybeMessage< ::wuk::im::Message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::wuk::im::Message >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
