// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WukAccount.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_WukAccount_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_WukAccount_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_WukAccount_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_WukAccount_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_WukAccount_2eproto;
namespace wuk {
namespace im {
class Message;
struct MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> ::wuk::im::Message* Arena::CreateMaybeMessage<::wuk::im::Message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wuk {
namespace im {

enum ACCOUNT_STATUS : int {
  UNDEFINED = 0,
  NORMAL = 1,
  BANNED = 2,
  MUTED = 3,
  DELETED = 4,
  ACCOUNT_STATUS_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ACCOUNT_STATUS_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ACCOUNT_STATUS_IsValid(int value);
constexpr ACCOUNT_STATUS ACCOUNT_STATUS_MIN = UNDEFINED;
constexpr ACCOUNT_STATUS ACCOUNT_STATUS_MAX = DELETED;
constexpr int ACCOUNT_STATUS_ARRAYSIZE = ACCOUNT_STATUS_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ACCOUNT_STATUS_descriptor();
template<typename T>
inline const std::string& ACCOUNT_STATUS_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ACCOUNT_STATUS>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ACCOUNT_STATUS_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ACCOUNT_STATUS_descriptor(), enum_t_value);
}
inline bool ACCOUNT_STATUS_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ACCOUNT_STATUS* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ACCOUNT_STATUS>(
    ACCOUNT_STATUS_descriptor(), name, value);
}
// ===================================================================

class Message final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wuk.im.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() override;
  explicit PROTOBUF_CONSTEXPR Message(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Message& default_instance() {
    return *internal_default_instance();
  }
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Message& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Message& from) {
    Message::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wuk.im.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMNameFieldNumber = 2,
    kMSaltFieldNumber = 3,
    kMHashFieldNumber = 4,
    kMUidFieldNumber = 1,
    kMCreatedFieldNumber = 6,
    kMModifiedFieldNumber = 7,
    kMAccessedFieldNumber = 8,
    kMDeletedFieldNumber = 9,
    kMStatusFieldNumber = 5,
  };
  // string m_name = 2;
  void clear_m_name();
  const std::string& m_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_name();
  PROTOBUF_NODISCARD std::string* release_m_name();
  void set_allocated_m_name(std::string* m_name);
  private:
  const std::string& _internal_m_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_name(const std::string& value);
  std::string* _internal_mutable_m_name();
  public:

  // bytes m_salt = 3;
  void clear_m_salt();
  const std::string& m_salt() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_salt(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_salt();
  PROTOBUF_NODISCARD std::string* release_m_salt();
  void set_allocated_m_salt(std::string* m_salt);
  private:
  const std::string& _internal_m_salt() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_salt(const std::string& value);
  std::string* _internal_mutable_m_salt();
  public:

  // bytes m_hash = 4;
  void clear_m_hash();
  const std::string& m_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_hash();
  PROTOBUF_NODISCARD std::string* release_m_hash();
  void set_allocated_m_hash(std::string* m_hash);
  private:
  const std::string& _internal_m_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_hash(const std::string& value);
  std::string* _internal_mutable_m_hash();
  public:

  // int64 m_uid = 1;
  void clear_m_uid();
  int64_t m_uid() const;
  void set_m_uid(int64_t value);
  private:
  int64_t _internal_m_uid() const;
  void _internal_set_m_uid(int64_t value);
  public:

  // double m_created = 6;
  void clear_m_created();
  double m_created() const;
  void set_m_created(double value);
  private:
  double _internal_m_created() const;
  void _internal_set_m_created(double value);
  public:

  // double m_modified = 7;
  void clear_m_modified();
  double m_modified() const;
  void set_m_modified(double value);
  private:
  double _internal_m_modified() const;
  void _internal_set_m_modified(double value);
  public:

  // double m_accessed = 8;
  void clear_m_accessed();
  double m_accessed() const;
  void set_m_accessed(double value);
  private:
  double _internal_m_accessed() const;
  void _internal_set_m_accessed(double value);
  public:

  // double m_deleted = 9;
  void clear_m_deleted();
  double m_deleted() const;
  void set_m_deleted(double value);
  private:
  double _internal_m_deleted() const;
  void _internal_set_m_deleted(double value);
  public:

  // .wuk.im.ACCOUNT_STATUS m_status = 5;
  void clear_m_status();
  ::wuk::im::ACCOUNT_STATUS m_status() const;
  void set_m_status(::wuk::im::ACCOUNT_STATUS value);
  private:
  ::wuk::im::ACCOUNT_STATUS _internal_m_status() const;
  void _internal_set_m_status(::wuk::im::ACCOUNT_STATUS value);
  public:

  // @@protoc_insertion_point(class_scope:wuk.im.Message)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_salt_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_hash_;
    int64_t m_uid_;
    double m_created_;
    double m_modified_;
    double m_accessed_;
    double m_deleted_;
    int m_status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WukAccount_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Message

// int64 m_uid = 1;
inline void Message::clear_m_uid() {
  _impl_.m_uid_ = int64_t{0};
}
inline int64_t Message::_internal_m_uid() const {
  return _impl_.m_uid_;
}
inline int64_t Message::m_uid() const {
  // @@protoc_insertion_point(field_get:wuk.im.Message.m_uid)
  return _internal_m_uid();
}
inline void Message::_internal_set_m_uid(int64_t value) {
  
  _impl_.m_uid_ = value;
}
inline void Message::set_m_uid(int64_t value) {
  _internal_set_m_uid(value);
  // @@protoc_insertion_point(field_set:wuk.im.Message.m_uid)
}

// string m_name = 2;
inline void Message::clear_m_name() {
  _impl_.m_name_.ClearToEmpty();
}
inline const std::string& Message::m_name() const {
  // @@protoc_insertion_point(field_get:wuk.im.Message.m_name)
  return _internal_m_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_m_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.Message.m_name)
}
inline std::string* Message::mutable_m_name() {
  std::string* _s = _internal_mutable_m_name();
  // @@protoc_insertion_point(field_mutable:wuk.im.Message.m_name)
  return _s;
}
inline const std::string& Message::_internal_m_name() const {
  return _impl_.m_name_.Get();
}
inline void Message::_internal_set_m_name(const std::string& value) {
  
  _impl_.m_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_m_name() {
  
  return _impl_.m_name_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_m_name() {
  // @@protoc_insertion_point(field_release:wuk.im.Message.m_name)
  return _impl_.m_name_.Release();
}
inline void Message::set_allocated_m_name(std::string* m_name) {
  if (m_name != nullptr) {
    
  } else {
    
  }
  _impl_.m_name_.SetAllocated(m_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_name_.IsDefault()) {
    _impl_.m_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.Message.m_name)
}

// bytes m_salt = 3;
inline void Message::clear_m_salt() {
  _impl_.m_salt_.ClearToEmpty();
}
inline const std::string& Message::m_salt() const {
  // @@protoc_insertion_point(field_get:wuk.im.Message.m_salt)
  return _internal_m_salt();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_m_salt(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_salt_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.Message.m_salt)
}
inline std::string* Message::mutable_m_salt() {
  std::string* _s = _internal_mutable_m_salt();
  // @@protoc_insertion_point(field_mutable:wuk.im.Message.m_salt)
  return _s;
}
inline const std::string& Message::_internal_m_salt() const {
  return _impl_.m_salt_.Get();
}
inline void Message::_internal_set_m_salt(const std::string& value) {
  
  _impl_.m_salt_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_m_salt() {
  
  return _impl_.m_salt_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_m_salt() {
  // @@protoc_insertion_point(field_release:wuk.im.Message.m_salt)
  return _impl_.m_salt_.Release();
}
inline void Message::set_allocated_m_salt(std::string* m_salt) {
  if (m_salt != nullptr) {
    
  } else {
    
  }
  _impl_.m_salt_.SetAllocated(m_salt, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_salt_.IsDefault()) {
    _impl_.m_salt_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.Message.m_salt)
}

// bytes m_hash = 4;
inline void Message::clear_m_hash() {
  _impl_.m_hash_.ClearToEmpty();
}
inline const std::string& Message::m_hash() const {
  // @@protoc_insertion_point(field_get:wuk.im.Message.m_hash)
  return _internal_m_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_m_hash(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_hash_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.Message.m_hash)
}
inline std::string* Message::mutable_m_hash() {
  std::string* _s = _internal_mutable_m_hash();
  // @@protoc_insertion_point(field_mutable:wuk.im.Message.m_hash)
  return _s;
}
inline const std::string& Message::_internal_m_hash() const {
  return _impl_.m_hash_.Get();
}
inline void Message::_internal_set_m_hash(const std::string& value) {
  
  _impl_.m_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_m_hash() {
  
  return _impl_.m_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_m_hash() {
  // @@protoc_insertion_point(field_release:wuk.im.Message.m_hash)
  return _impl_.m_hash_.Release();
}
inline void Message::set_allocated_m_hash(std::string* m_hash) {
  if (m_hash != nullptr) {
    
  } else {
    
  }
  _impl_.m_hash_.SetAllocated(m_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_hash_.IsDefault()) {
    _impl_.m_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.Message.m_hash)
}

// .wuk.im.ACCOUNT_STATUS m_status = 5;
inline void Message::clear_m_status() {
  _impl_.m_status_ = 0;
}
inline ::wuk::im::ACCOUNT_STATUS Message::_internal_m_status() const {
  return static_cast< ::wuk::im::ACCOUNT_STATUS >(_impl_.m_status_);
}
inline ::wuk::im::ACCOUNT_STATUS Message::m_status() const {
  // @@protoc_insertion_point(field_get:wuk.im.Message.m_status)
  return _internal_m_status();
}
inline void Message::_internal_set_m_status(::wuk::im::ACCOUNT_STATUS value) {
  
  _impl_.m_status_ = value;
}
inline void Message::set_m_status(::wuk::im::ACCOUNT_STATUS value) {
  _internal_set_m_status(value);
  // @@protoc_insertion_point(field_set:wuk.im.Message.m_status)
}

// double m_created = 6;
inline void Message::clear_m_created() {
  _impl_.m_created_ = 0;
}
inline double Message::_internal_m_created() const {
  return _impl_.m_created_;
}
inline double Message::m_created() const {
  // @@protoc_insertion_point(field_get:wuk.im.Message.m_created)
  return _internal_m_created();
}
inline void Message::_internal_set_m_created(double value) {
  
  _impl_.m_created_ = value;
}
inline void Message::set_m_created(double value) {
  _internal_set_m_created(value);
  // @@protoc_insertion_point(field_set:wuk.im.Message.m_created)
}

// double m_modified = 7;
inline void Message::clear_m_modified() {
  _impl_.m_modified_ = 0;
}
inline double Message::_internal_m_modified() const {
  return _impl_.m_modified_;
}
inline double Message::m_modified() const {
  // @@protoc_insertion_point(field_get:wuk.im.Message.m_modified)
  return _internal_m_modified();
}
inline void Message::_internal_set_m_modified(double value) {
  
  _impl_.m_modified_ = value;
}
inline void Message::set_m_modified(double value) {
  _internal_set_m_modified(value);
  // @@protoc_insertion_point(field_set:wuk.im.Message.m_modified)
}

// double m_accessed = 8;
inline void Message::clear_m_accessed() {
  _impl_.m_accessed_ = 0;
}
inline double Message::_internal_m_accessed() const {
  return _impl_.m_accessed_;
}
inline double Message::m_accessed() const {
  // @@protoc_insertion_point(field_get:wuk.im.Message.m_accessed)
  return _internal_m_accessed();
}
inline void Message::_internal_set_m_accessed(double value) {
  
  _impl_.m_accessed_ = value;
}
inline void Message::set_m_accessed(double value) {
  _internal_set_m_accessed(value);
  // @@protoc_insertion_point(field_set:wuk.im.Message.m_accessed)
}

// double m_deleted = 9;
inline void Message::clear_m_deleted() {
  _impl_.m_deleted_ = 0;
}
inline double Message::_internal_m_deleted() const {
  return _impl_.m_deleted_;
}
inline double Message::m_deleted() const {
  // @@protoc_insertion_point(field_get:wuk.im.Message.m_deleted)
  return _internal_m_deleted();
}
inline void Message::_internal_set_m_deleted(double value) {
  
  _impl_.m_deleted_ = value;
}
inline void Message::set_m_deleted(double value) {
  _internal_set_m_deleted(value);
  // @@protoc_insertion_point(field_set:wuk.im.Message.m_deleted)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace im
}  // namespace wuk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::wuk::im::ACCOUNT_STATUS> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::wuk::im::ACCOUNT_STATUS>() {
  return ::wuk::im::ACCOUNT_STATUS_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_WukAccount_2eproto
