// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_login_5frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_login_5frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "packet.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_login_5frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_login_5frequest_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_login_5frequest_2eproto;
namespace wuk {
namespace im {
namespace auth {
class LoginRequest;
struct LoginRequestDefaultTypeInternal;
extern LoginRequestDefaultTypeInternal _LoginRequest_default_instance_;
}  // namespace auth
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> ::wuk::im::auth::LoginRequest* Arena::CreateMaybeMessage<::wuk::im::auth::LoginRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wuk {
namespace im {
namespace auth {

// ===================================================================

class LoginRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wuk.im.auth.LoginRequest) */ {
 public:
  inline LoginRequest() : LoginRequest(nullptr) {}
  ~LoginRequest() override;
  explicit PROTOBUF_CONSTEXPR LoginRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginRequest(const LoginRequest& from);
  LoginRequest(LoginRequest&& from) noexcept
    : LoginRequest() {
    *this = ::std::move(from);
  }

  inline LoginRequest& operator=(const LoginRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginRequest& operator=(LoginRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginRequest& default_instance() {
    return *internal_default_instance();
  }
  enum CredentialCase {
    kPassword = 3,
    kToken = 4,
    kSmsCode = 5,
    CREDENTIAL_NOT_SET = 0,
  };

  static inline const LoginRequest* internal_default_instance() {
    return reinterpret_cast<const LoginRequest*>(
               &_LoginRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LoginRequest& a, LoginRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LoginRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LoginRequest& from) {
    LoginRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wuk.im.auth.LoginRequest";
  }
  protected:
  explicit LoginRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMAccountFieldNumber = 2,
    kMBaseFieldNumber = 1,
    kPasswordFieldNumber = 3,
    kTokenFieldNumber = 4,
    kSmsCodeFieldNumber = 5,
  };
  // string m_account = 2;
  void clear_m_account();
  const std::string& m_account() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_account(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_account();
  PROTOBUF_NODISCARD std::string* release_m_account();
  void set_allocated_m_account(std::string* m_account);
  private:
  const std::string& _internal_m_account() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_account(const std::string& value);
  std::string* _internal_mutable_m_account();
  public:

  // .wuk.im.base.BaseRequest m_base = 1;
  bool has_m_base() const;
  private:
  bool _internal_has_m_base() const;
  public:
  void clear_m_base();
  const ::wuk::im::base::BaseRequest& m_base() const;
  PROTOBUF_NODISCARD ::wuk::im::base::BaseRequest* release_m_base();
  ::wuk::im::base::BaseRequest* mutable_m_base();
  void set_allocated_m_base(::wuk::im::base::BaseRequest* m_base);
  private:
  const ::wuk::im::base::BaseRequest& _internal_m_base() const;
  ::wuk::im::base::BaseRequest* _internal_mutable_m_base();
  public:
  void unsafe_arena_set_allocated_m_base(
      ::wuk::im::base::BaseRequest* m_base);
  ::wuk::im::base::BaseRequest* unsafe_arena_release_m_base();

  // string password = 3;
  bool has_password() const;
  private:
  bool _internal_has_password() const;
  public:
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string token = 4;
  bool has_token() const;
  private:
  bool _internal_has_token() const;
  public:
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // string sms_code = 5;
  bool has_sms_code() const;
  private:
  bool _internal_has_sms_code() const;
  public:
  void clear_sms_code();
  const std::string& sms_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sms_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sms_code();
  PROTOBUF_NODISCARD std::string* release_sms_code();
  void set_allocated_sms_code(std::string* sms_code);
  private:
  const std::string& _internal_sms_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sms_code(const std::string& value);
  std::string* _internal_mutable_sms_code();
  public:

  void clear_credential();
  CredentialCase credential_case() const;
  // @@protoc_insertion_point(class_scope:wuk.im.auth.LoginRequest)
 private:
  class _Internal;
  void set_has_password();
  void set_has_token();
  void set_has_sms_code();

  inline bool has_credential() const;
  inline void clear_has_credential();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_account_;
    ::wuk::im::base::BaseRequest* m_base_;
    union CredentialUnion {
      constexpr CredentialUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sms_code_;
    } credential_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_login_5frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LoginRequest

// .wuk.im.base.BaseRequest m_base = 1;
inline bool LoginRequest::_internal_has_m_base() const {
  return this != internal_default_instance() && _impl_.m_base_ != nullptr;
}
inline bool LoginRequest::has_m_base() const {
  return _internal_has_m_base();
}
inline const ::wuk::im::base::BaseRequest& LoginRequest::_internal_m_base() const {
  const ::wuk::im::base::BaseRequest* p = _impl_.m_base_;
  return p != nullptr ? *p : reinterpret_cast<const ::wuk::im::base::BaseRequest&>(
      ::wuk::im::base::_BaseRequest_default_instance_);
}
inline const ::wuk::im::base::BaseRequest& LoginRequest::m_base() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginRequest.m_base)
  return _internal_m_base();
}
inline void LoginRequest::unsafe_arena_set_allocated_m_base(
    ::wuk::im::base::BaseRequest* m_base) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.m_base_);
  }
  _impl_.m_base_ = m_base;
  if (m_base) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wuk.im.auth.LoginRequest.m_base)
}
inline ::wuk::im::base::BaseRequest* LoginRequest::release_m_base() {
  
  ::wuk::im::base::BaseRequest* temp = _impl_.m_base_;
  _impl_.m_base_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wuk::im::base::BaseRequest* LoginRequest::unsafe_arena_release_m_base() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.LoginRequest.m_base)
  
  ::wuk::im::base::BaseRequest* temp = _impl_.m_base_;
  _impl_.m_base_ = nullptr;
  return temp;
}
inline ::wuk::im::base::BaseRequest* LoginRequest::_internal_mutable_m_base() {
  
  if (_impl_.m_base_ == nullptr) {
    auto* p = CreateMaybeMessage<::wuk::im::base::BaseRequest>(GetArenaForAllocation());
    _impl_.m_base_ = p;
  }
  return _impl_.m_base_;
}
inline ::wuk::im::base::BaseRequest* LoginRequest::mutable_m_base() {
  ::wuk::im::base::BaseRequest* _msg = _internal_mutable_m_base();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.LoginRequest.m_base)
  return _msg;
}
inline void LoginRequest::set_allocated_m_base(::wuk::im::base::BaseRequest* m_base) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.m_base_);
  }
  if (m_base) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(m_base));
    if (message_arena != submessage_arena) {
      m_base = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m_base, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.m_base_ = m_base;
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.LoginRequest.m_base)
}

// string password = 3;
inline bool LoginRequest::_internal_has_password() const {
  return credential_case() == kPassword;
}
inline bool LoginRequest::has_password() const {
  return _internal_has_password();
}
inline void LoginRequest::set_has_password() {
  _impl_._oneof_case_[0] = kPassword;
}
inline void LoginRequest::clear_password() {
  if (_internal_has_password()) {
    _impl_.credential_.password_.Destroy();
    clear_has_credential();
  }
}
inline const std::string& LoginRequest::password() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginRequest.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline void LoginRequest::set_password(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_password()) {
    clear_credential();
    set_has_password();
    _impl_.credential_.password_.InitDefault();
  }
  _impl_.credential_.password_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.auth.LoginRequest.password)
}
inline std::string* LoginRequest::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.LoginRequest.password)
  return _s;
}
inline const std::string& LoginRequest::_internal_password() const {
  if (_internal_has_password()) {
    return _impl_.credential_.password_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void LoginRequest::_internal_set_password(const std::string& value) {
  if (!_internal_has_password()) {
    clear_credential();
    set_has_password();
    _impl_.credential_.password_.InitDefault();
  }
  _impl_.credential_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginRequest::_internal_mutable_password() {
  if (!_internal_has_password()) {
    clear_credential();
    set_has_password();
    _impl_.credential_.password_.InitDefault();
  }
  return _impl_.credential_.password_.Mutable(      GetArenaForAllocation());
}
inline std::string* LoginRequest::release_password() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.LoginRequest.password)
  if (_internal_has_password()) {
    clear_has_credential();
    return _impl_.credential_.password_.Release();
  } else {
    return nullptr;
  }
}
inline void LoginRequest::set_allocated_password(std::string* password) {
  if (has_credential()) {
    clear_credential();
  }
  if (password != nullptr) {
    set_has_password();
    _impl_.credential_.password_.InitAllocated(password, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.LoginRequest.password)
}

// string token = 4;
inline bool LoginRequest::_internal_has_token() const {
  return credential_case() == kToken;
}
inline bool LoginRequest::has_token() const {
  return _internal_has_token();
}
inline void LoginRequest::set_has_token() {
  _impl_._oneof_case_[0] = kToken;
}
inline void LoginRequest::clear_token() {
  if (_internal_has_token()) {
    _impl_.credential_.token_.Destroy();
    clear_has_credential();
  }
}
inline const std::string& LoginRequest::token() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginRequest.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline void LoginRequest::set_token(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_token()) {
    clear_credential();
    set_has_token();
    _impl_.credential_.token_.InitDefault();
  }
  _impl_.credential_.token_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.auth.LoginRequest.token)
}
inline std::string* LoginRequest::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.LoginRequest.token)
  return _s;
}
inline const std::string& LoginRequest::_internal_token() const {
  if (_internal_has_token()) {
    return _impl_.credential_.token_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void LoginRequest::_internal_set_token(const std::string& value) {
  if (!_internal_has_token()) {
    clear_credential();
    set_has_token();
    _impl_.credential_.token_.InitDefault();
  }
  _impl_.credential_.token_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginRequest::_internal_mutable_token() {
  if (!_internal_has_token()) {
    clear_credential();
    set_has_token();
    _impl_.credential_.token_.InitDefault();
  }
  return _impl_.credential_.token_.Mutable(      GetArenaForAllocation());
}
inline std::string* LoginRequest::release_token() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.LoginRequest.token)
  if (_internal_has_token()) {
    clear_has_credential();
    return _impl_.credential_.token_.Release();
  } else {
    return nullptr;
  }
}
inline void LoginRequest::set_allocated_token(std::string* token) {
  if (has_credential()) {
    clear_credential();
  }
  if (token != nullptr) {
    set_has_token();
    _impl_.credential_.token_.InitAllocated(token, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.LoginRequest.token)
}

// string sms_code = 5;
inline bool LoginRequest::_internal_has_sms_code() const {
  return credential_case() == kSmsCode;
}
inline bool LoginRequest::has_sms_code() const {
  return _internal_has_sms_code();
}
inline void LoginRequest::set_has_sms_code() {
  _impl_._oneof_case_[0] = kSmsCode;
}
inline void LoginRequest::clear_sms_code() {
  if (_internal_has_sms_code()) {
    _impl_.credential_.sms_code_.Destroy();
    clear_has_credential();
  }
}
inline const std::string& LoginRequest::sms_code() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginRequest.sms_code)
  return _internal_sms_code();
}
template <typename ArgT0, typename... ArgT>
inline void LoginRequest::set_sms_code(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_sms_code()) {
    clear_credential();
    set_has_sms_code();
    _impl_.credential_.sms_code_.InitDefault();
  }
  _impl_.credential_.sms_code_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.auth.LoginRequest.sms_code)
}
inline std::string* LoginRequest::mutable_sms_code() {
  std::string* _s = _internal_mutable_sms_code();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.LoginRequest.sms_code)
  return _s;
}
inline const std::string& LoginRequest::_internal_sms_code() const {
  if (_internal_has_sms_code()) {
    return _impl_.credential_.sms_code_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void LoginRequest::_internal_set_sms_code(const std::string& value) {
  if (!_internal_has_sms_code()) {
    clear_credential();
    set_has_sms_code();
    _impl_.credential_.sms_code_.InitDefault();
  }
  _impl_.credential_.sms_code_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginRequest::_internal_mutable_sms_code() {
  if (!_internal_has_sms_code()) {
    clear_credential();
    set_has_sms_code();
    _impl_.credential_.sms_code_.InitDefault();
  }
  return _impl_.credential_.sms_code_.Mutable(      GetArenaForAllocation());
}
inline std::string* LoginRequest::release_sms_code() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.LoginRequest.sms_code)
  if (_internal_has_sms_code()) {
    clear_has_credential();
    return _impl_.credential_.sms_code_.Release();
  } else {
    return nullptr;
  }
}
inline void LoginRequest::set_allocated_sms_code(std::string* sms_code) {
  if (has_credential()) {
    clear_credential();
  }
  if (sms_code != nullptr) {
    set_has_sms_code();
    _impl_.credential_.sms_code_.InitAllocated(sms_code, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.LoginRequest.sms_code)
}

// string m_account = 2;
inline void LoginRequest::clear_m_account() {
  _impl_.m_account_.ClearToEmpty();
}
inline const std::string& LoginRequest::m_account() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginRequest.m_account)
  return _internal_m_account();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginRequest::set_m_account(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_account_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.auth.LoginRequest.m_account)
}
inline std::string* LoginRequest::mutable_m_account() {
  std::string* _s = _internal_mutable_m_account();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.LoginRequest.m_account)
  return _s;
}
inline const std::string& LoginRequest::_internal_m_account() const {
  return _impl_.m_account_.Get();
}
inline void LoginRequest::_internal_set_m_account(const std::string& value) {
  
  _impl_.m_account_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginRequest::_internal_mutable_m_account() {
  
  return _impl_.m_account_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginRequest::release_m_account() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.LoginRequest.m_account)
  return _impl_.m_account_.Release();
}
inline void LoginRequest::set_allocated_m_account(std::string* m_account) {
  if (m_account != nullptr) {
    
  } else {
    
  }
  _impl_.m_account_.SetAllocated(m_account, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_account_.IsDefault()) {
    _impl_.m_account_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.LoginRequest.m_account)
}

inline bool LoginRequest::has_credential() const {
  return credential_case() != CREDENTIAL_NOT_SET;
}
inline void LoginRequest::clear_has_credential() {
  _impl_._oneof_case_[0] = CREDENTIAL_NOT_SET;
}
inline LoginRequest::CredentialCase LoginRequest::credential_case() const {
  return LoginRequest::CredentialCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace auth
}  // namespace im
}  // namespace wuk

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_login_5frequest_2eproto
