// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_login_5fresponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_login_5fresponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "packet.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_login_5fresponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_login_5fresponse_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_login_5fresponse_2eproto;
namespace wuk {
namespace im {
namespace auth {
class LoginResponse;
struct LoginResponseDefaultTypeInternal;
extern LoginResponseDefaultTypeInternal _LoginResponse_default_instance_;
class UserInfo;
struct UserInfoDefaultTypeInternal;
extern UserInfoDefaultTypeInternal _UserInfo_default_instance_;
}  // namespace auth
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> ::wuk::im::auth::LoginResponse* Arena::CreateMaybeMessage<::wuk::im::auth::LoginResponse>(Arena*);
template<> ::wuk::im::auth::UserInfo* Arena::CreateMaybeMessage<::wuk::im::auth::UserInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wuk {
namespace im {
namespace auth {

enum ResponseType : int {
  RESPONSE_TYPE_SUCCESS = 0,
  RESPONSE_TYPE_FAILED = 1,
  RESPONSE_TYPE_AUTH_FAILED = 2,
  RESPONSE_TYPE_NOT_FOUND = 3,
  RESPONSE_TYPE_TOKEN_EXPIRED = 4,
  RESPONSE_TYPE_WAITWAITWAIT = 5,
  ResponseType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ResponseType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ResponseType_IsValid(int value);
constexpr ResponseType ResponseType_MIN = RESPONSE_TYPE_SUCCESS;
constexpr ResponseType ResponseType_MAX = RESPONSE_TYPE_WAITWAITWAIT;
constexpr int ResponseType_ARRAYSIZE = ResponseType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResponseType_descriptor();
template<typename T>
inline const std::string& ResponseType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ResponseType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ResponseType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ResponseType_descriptor(), enum_t_value);
}
inline bool ResponseType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ResponseType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ResponseType>(
    ResponseType_descriptor(), name, value);
}
// ===================================================================

class UserInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wuk.im.auth.UserInfo) */ {
 public:
  inline UserInfo() : UserInfo(nullptr) {}
  ~UserInfo() override;
  explicit PROTOBUF_CONSTEXPR UserInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UserInfo(const UserInfo& from);
  UserInfo(UserInfo&& from) noexcept
    : UserInfo() {
    *this = ::std::move(from);
  }

  inline UserInfo& operator=(const UserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserInfo& operator=(UserInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserInfo* internal_default_instance() {
    return reinterpret_cast<const UserInfo*>(
               &_UserInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UserInfo& a, UserInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(UserInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UserInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UserInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UserInfo& from) {
    UserInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wuk.im.auth.UserInfo";
  }
  protected:
  explicit UserInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMProfilePictureFieldNumber = 1,
    kMUsernameFieldNumber = 2,
    kMBioFieldNumber = 3,
  };
  // string m_profile_picture = 1;
  void clear_m_profile_picture();
  const std::string& m_profile_picture() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_profile_picture(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_profile_picture();
  PROTOBUF_NODISCARD std::string* release_m_profile_picture();
  void set_allocated_m_profile_picture(std::string* m_profile_picture);
  private:
  const std::string& _internal_m_profile_picture() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_profile_picture(const std::string& value);
  std::string* _internal_mutable_m_profile_picture();
  public:

  // string m_username = 2;
  void clear_m_username();
  const std::string& m_username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_username();
  PROTOBUF_NODISCARD std::string* release_m_username();
  void set_allocated_m_username(std::string* m_username);
  private:
  const std::string& _internal_m_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_username(const std::string& value);
  std::string* _internal_mutable_m_username();
  public:

  // string m_bio = 3;
  void clear_m_bio();
  const std::string& m_bio() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_bio(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_bio();
  PROTOBUF_NODISCARD std::string* release_m_bio();
  void set_allocated_m_bio(std::string* m_bio);
  private:
  const std::string& _internal_m_bio() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_bio(const std::string& value);
  std::string* _internal_mutable_m_bio();
  public:

  // @@protoc_insertion_point(class_scope:wuk.im.auth.UserInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_profile_picture_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_bio_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_login_5fresponse_2eproto;
};
// -------------------------------------------------------------------

class LoginResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wuk.im.auth.LoginResponse) */ {
 public:
  inline LoginResponse() : LoginResponse(nullptr) {}
  ~LoginResponse() override;
  explicit PROTOBUF_CONSTEXPR LoginResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginResponse(const LoginResponse& from);
  LoginResponse(LoginResponse&& from) noexcept
    : LoginResponse() {
    *this = ::std::move(from);
  }

  inline LoginResponse& operator=(const LoginResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginResponse& operator=(LoginResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginResponse* internal_default_instance() {
    return reinterpret_cast<const LoginResponse*>(
               &_LoginResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LoginResponse& a, LoginResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LoginResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LoginResponse& from) {
    LoginResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wuk.im.auth.LoginResponse";
  }
  protected:
  explicit LoginResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMMessageFieldNumber = 3,
    kMTokenFieldNumber = 4,
    kMBaseFieldNumber = 1,
    kMUserFieldNumber = 5,
    kMCodeFieldNumber = 2,
  };
  // string m_message = 3;
  void clear_m_message();
  const std::string& m_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_message();
  PROTOBUF_NODISCARD std::string* release_m_message();
  void set_allocated_m_message(std::string* m_message);
  private:
  const std::string& _internal_m_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_message(const std::string& value);
  std::string* _internal_mutable_m_message();
  public:

  // string m_token = 4;
  void clear_m_token();
  const std::string& m_token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_token();
  PROTOBUF_NODISCARD std::string* release_m_token();
  void set_allocated_m_token(std::string* m_token);
  private:
  const std::string& _internal_m_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_token(const std::string& value);
  std::string* _internal_mutable_m_token();
  public:

  // .wuk.im.base.BaseRequest m_base = 1;
  bool has_m_base() const;
  private:
  bool _internal_has_m_base() const;
  public:
  void clear_m_base();
  const ::wuk::im::base::BaseRequest& m_base() const;
  PROTOBUF_NODISCARD ::wuk::im::base::BaseRequest* release_m_base();
  ::wuk::im::base::BaseRequest* mutable_m_base();
  void set_allocated_m_base(::wuk::im::base::BaseRequest* m_base);
  private:
  const ::wuk::im::base::BaseRequest& _internal_m_base() const;
  ::wuk::im::base::BaseRequest* _internal_mutable_m_base();
  public:
  void unsafe_arena_set_allocated_m_base(
      ::wuk::im::base::BaseRequest* m_base);
  ::wuk::im::base::BaseRequest* unsafe_arena_release_m_base();

  // .wuk.im.auth.UserInfo m_user = 5;
  bool has_m_user() const;
  private:
  bool _internal_has_m_user() const;
  public:
  void clear_m_user();
  const ::wuk::im::auth::UserInfo& m_user() const;
  PROTOBUF_NODISCARD ::wuk::im::auth::UserInfo* release_m_user();
  ::wuk::im::auth::UserInfo* mutable_m_user();
  void set_allocated_m_user(::wuk::im::auth::UserInfo* m_user);
  private:
  const ::wuk::im::auth::UserInfo& _internal_m_user() const;
  ::wuk::im::auth::UserInfo* _internal_mutable_m_user();
  public:
  void unsafe_arena_set_allocated_m_user(
      ::wuk::im::auth::UserInfo* m_user);
  ::wuk::im::auth::UserInfo* unsafe_arena_release_m_user();

  // .wuk.im.auth.ResponseType m_code = 2;
  void clear_m_code();
  ::wuk::im::auth::ResponseType m_code() const;
  void set_m_code(::wuk::im::auth::ResponseType value);
  private:
  ::wuk::im::auth::ResponseType _internal_m_code() const;
  void _internal_set_m_code(::wuk::im::auth::ResponseType value);
  public:

  // @@protoc_insertion_point(class_scope:wuk.im.auth.LoginResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_message_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_token_;
    ::wuk::im::base::BaseRequest* m_base_;
    ::wuk::im::auth::UserInfo* m_user_;
    int m_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_login_5fresponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserInfo

// string m_profile_picture = 1;
inline void UserInfo::clear_m_profile_picture() {
  _impl_.m_profile_picture_.ClearToEmpty();
}
inline const std::string& UserInfo::m_profile_picture() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.UserInfo.m_profile_picture)
  return _internal_m_profile_picture();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UserInfo::set_m_profile_picture(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_profile_picture_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.auth.UserInfo.m_profile_picture)
}
inline std::string* UserInfo::mutable_m_profile_picture() {
  std::string* _s = _internal_mutable_m_profile_picture();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.UserInfo.m_profile_picture)
  return _s;
}
inline const std::string& UserInfo::_internal_m_profile_picture() const {
  return _impl_.m_profile_picture_.Get();
}
inline void UserInfo::_internal_set_m_profile_picture(const std::string& value) {
  
  _impl_.m_profile_picture_.Set(value, GetArenaForAllocation());
}
inline std::string* UserInfo::_internal_mutable_m_profile_picture() {
  
  return _impl_.m_profile_picture_.Mutable(GetArenaForAllocation());
}
inline std::string* UserInfo::release_m_profile_picture() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.UserInfo.m_profile_picture)
  return _impl_.m_profile_picture_.Release();
}
inline void UserInfo::set_allocated_m_profile_picture(std::string* m_profile_picture) {
  if (m_profile_picture != nullptr) {
    
  } else {
    
  }
  _impl_.m_profile_picture_.SetAllocated(m_profile_picture, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_profile_picture_.IsDefault()) {
    _impl_.m_profile_picture_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.UserInfo.m_profile_picture)
}

// string m_username = 2;
inline void UserInfo::clear_m_username() {
  _impl_.m_username_.ClearToEmpty();
}
inline const std::string& UserInfo::m_username() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.UserInfo.m_username)
  return _internal_m_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UserInfo::set_m_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.auth.UserInfo.m_username)
}
inline std::string* UserInfo::mutable_m_username() {
  std::string* _s = _internal_mutable_m_username();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.UserInfo.m_username)
  return _s;
}
inline const std::string& UserInfo::_internal_m_username() const {
  return _impl_.m_username_.Get();
}
inline void UserInfo::_internal_set_m_username(const std::string& value) {
  
  _impl_.m_username_.Set(value, GetArenaForAllocation());
}
inline std::string* UserInfo::_internal_mutable_m_username() {
  
  return _impl_.m_username_.Mutable(GetArenaForAllocation());
}
inline std::string* UserInfo::release_m_username() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.UserInfo.m_username)
  return _impl_.m_username_.Release();
}
inline void UserInfo::set_allocated_m_username(std::string* m_username) {
  if (m_username != nullptr) {
    
  } else {
    
  }
  _impl_.m_username_.SetAllocated(m_username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_username_.IsDefault()) {
    _impl_.m_username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.UserInfo.m_username)
}

// string m_bio = 3;
inline void UserInfo::clear_m_bio() {
  _impl_.m_bio_.ClearToEmpty();
}
inline const std::string& UserInfo::m_bio() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.UserInfo.m_bio)
  return _internal_m_bio();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UserInfo::set_m_bio(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_bio_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.auth.UserInfo.m_bio)
}
inline std::string* UserInfo::mutable_m_bio() {
  std::string* _s = _internal_mutable_m_bio();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.UserInfo.m_bio)
  return _s;
}
inline const std::string& UserInfo::_internal_m_bio() const {
  return _impl_.m_bio_.Get();
}
inline void UserInfo::_internal_set_m_bio(const std::string& value) {
  
  _impl_.m_bio_.Set(value, GetArenaForAllocation());
}
inline std::string* UserInfo::_internal_mutable_m_bio() {
  
  return _impl_.m_bio_.Mutable(GetArenaForAllocation());
}
inline std::string* UserInfo::release_m_bio() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.UserInfo.m_bio)
  return _impl_.m_bio_.Release();
}
inline void UserInfo::set_allocated_m_bio(std::string* m_bio) {
  if (m_bio != nullptr) {
    
  } else {
    
  }
  _impl_.m_bio_.SetAllocated(m_bio, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_bio_.IsDefault()) {
    _impl_.m_bio_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.UserInfo.m_bio)
}

// -------------------------------------------------------------------

// LoginResponse

// .wuk.im.base.BaseRequest m_base = 1;
inline bool LoginResponse::_internal_has_m_base() const {
  return this != internal_default_instance() && _impl_.m_base_ != nullptr;
}
inline bool LoginResponse::has_m_base() const {
  return _internal_has_m_base();
}
inline const ::wuk::im::base::BaseRequest& LoginResponse::_internal_m_base() const {
  const ::wuk::im::base::BaseRequest* p = _impl_.m_base_;
  return p != nullptr ? *p : reinterpret_cast<const ::wuk::im::base::BaseRequest&>(
      ::wuk::im::base::_BaseRequest_default_instance_);
}
inline const ::wuk::im::base::BaseRequest& LoginResponse::m_base() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginResponse.m_base)
  return _internal_m_base();
}
inline void LoginResponse::unsafe_arena_set_allocated_m_base(
    ::wuk::im::base::BaseRequest* m_base) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.m_base_);
  }
  _impl_.m_base_ = m_base;
  if (m_base) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wuk.im.auth.LoginResponse.m_base)
}
inline ::wuk::im::base::BaseRequest* LoginResponse::release_m_base() {
  
  ::wuk::im::base::BaseRequest* temp = _impl_.m_base_;
  _impl_.m_base_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wuk::im::base::BaseRequest* LoginResponse::unsafe_arena_release_m_base() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.LoginResponse.m_base)
  
  ::wuk::im::base::BaseRequest* temp = _impl_.m_base_;
  _impl_.m_base_ = nullptr;
  return temp;
}
inline ::wuk::im::base::BaseRequest* LoginResponse::_internal_mutable_m_base() {
  
  if (_impl_.m_base_ == nullptr) {
    auto* p = CreateMaybeMessage<::wuk::im::base::BaseRequest>(GetArenaForAllocation());
    _impl_.m_base_ = p;
  }
  return _impl_.m_base_;
}
inline ::wuk::im::base::BaseRequest* LoginResponse::mutable_m_base() {
  ::wuk::im::base::BaseRequest* _msg = _internal_mutable_m_base();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.LoginResponse.m_base)
  return _msg;
}
inline void LoginResponse::set_allocated_m_base(::wuk::im::base::BaseRequest* m_base) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.m_base_);
  }
  if (m_base) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(m_base));
    if (message_arena != submessage_arena) {
      m_base = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m_base, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.m_base_ = m_base;
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.LoginResponse.m_base)
}

// .wuk.im.auth.ResponseType m_code = 2;
inline void LoginResponse::clear_m_code() {
  _impl_.m_code_ = 0;
}
inline ::wuk::im::auth::ResponseType LoginResponse::_internal_m_code() const {
  return static_cast< ::wuk::im::auth::ResponseType >(_impl_.m_code_);
}
inline ::wuk::im::auth::ResponseType LoginResponse::m_code() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginResponse.m_code)
  return _internal_m_code();
}
inline void LoginResponse::_internal_set_m_code(::wuk::im::auth::ResponseType value) {
  
  _impl_.m_code_ = value;
}
inline void LoginResponse::set_m_code(::wuk::im::auth::ResponseType value) {
  _internal_set_m_code(value);
  // @@protoc_insertion_point(field_set:wuk.im.auth.LoginResponse.m_code)
}

// string m_message = 3;
inline void LoginResponse::clear_m_message() {
  _impl_.m_message_.ClearToEmpty();
}
inline const std::string& LoginResponse::m_message() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginResponse.m_message)
  return _internal_m_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginResponse::set_m_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.auth.LoginResponse.m_message)
}
inline std::string* LoginResponse::mutable_m_message() {
  std::string* _s = _internal_mutable_m_message();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.LoginResponse.m_message)
  return _s;
}
inline const std::string& LoginResponse::_internal_m_message() const {
  return _impl_.m_message_.Get();
}
inline void LoginResponse::_internal_set_m_message(const std::string& value) {
  
  _impl_.m_message_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginResponse::_internal_mutable_m_message() {
  
  return _impl_.m_message_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginResponse::release_m_message() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.LoginResponse.m_message)
  return _impl_.m_message_.Release();
}
inline void LoginResponse::set_allocated_m_message(std::string* m_message) {
  if (m_message != nullptr) {
    
  } else {
    
  }
  _impl_.m_message_.SetAllocated(m_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_message_.IsDefault()) {
    _impl_.m_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.LoginResponse.m_message)
}

// string m_token = 4;
inline void LoginResponse::clear_m_token() {
  _impl_.m_token_.ClearToEmpty();
}
inline const std::string& LoginResponse::m_token() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginResponse.m_token)
  return _internal_m_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginResponse::set_m_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.auth.LoginResponse.m_token)
}
inline std::string* LoginResponse::mutable_m_token() {
  std::string* _s = _internal_mutable_m_token();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.LoginResponse.m_token)
  return _s;
}
inline const std::string& LoginResponse::_internal_m_token() const {
  return _impl_.m_token_.Get();
}
inline void LoginResponse::_internal_set_m_token(const std::string& value) {
  
  _impl_.m_token_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginResponse::_internal_mutable_m_token() {
  
  return _impl_.m_token_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginResponse::release_m_token() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.LoginResponse.m_token)
  return _impl_.m_token_.Release();
}
inline void LoginResponse::set_allocated_m_token(std::string* m_token) {
  if (m_token != nullptr) {
    
  } else {
    
  }
  _impl_.m_token_.SetAllocated(m_token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_token_.IsDefault()) {
    _impl_.m_token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.LoginResponse.m_token)
}

// .wuk.im.auth.UserInfo m_user = 5;
inline bool LoginResponse::_internal_has_m_user() const {
  return this != internal_default_instance() && _impl_.m_user_ != nullptr;
}
inline bool LoginResponse::has_m_user() const {
  return _internal_has_m_user();
}
inline void LoginResponse::clear_m_user() {
  if (GetArenaForAllocation() == nullptr && _impl_.m_user_ != nullptr) {
    delete _impl_.m_user_;
  }
  _impl_.m_user_ = nullptr;
}
inline const ::wuk::im::auth::UserInfo& LoginResponse::_internal_m_user() const {
  const ::wuk::im::auth::UserInfo* p = _impl_.m_user_;
  return p != nullptr ? *p : reinterpret_cast<const ::wuk::im::auth::UserInfo&>(
      ::wuk::im::auth::_UserInfo_default_instance_);
}
inline const ::wuk::im::auth::UserInfo& LoginResponse::m_user() const {
  // @@protoc_insertion_point(field_get:wuk.im.auth.LoginResponse.m_user)
  return _internal_m_user();
}
inline void LoginResponse::unsafe_arena_set_allocated_m_user(
    ::wuk::im::auth::UserInfo* m_user) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.m_user_);
  }
  _impl_.m_user_ = m_user;
  if (m_user) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wuk.im.auth.LoginResponse.m_user)
}
inline ::wuk::im::auth::UserInfo* LoginResponse::release_m_user() {
  
  ::wuk::im::auth::UserInfo* temp = _impl_.m_user_;
  _impl_.m_user_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wuk::im::auth::UserInfo* LoginResponse::unsafe_arena_release_m_user() {
  // @@protoc_insertion_point(field_release:wuk.im.auth.LoginResponse.m_user)
  
  ::wuk::im::auth::UserInfo* temp = _impl_.m_user_;
  _impl_.m_user_ = nullptr;
  return temp;
}
inline ::wuk::im::auth::UserInfo* LoginResponse::_internal_mutable_m_user() {
  
  if (_impl_.m_user_ == nullptr) {
    auto* p = CreateMaybeMessage<::wuk::im::auth::UserInfo>(GetArenaForAllocation());
    _impl_.m_user_ = p;
  }
  return _impl_.m_user_;
}
inline ::wuk::im::auth::UserInfo* LoginResponse::mutable_m_user() {
  ::wuk::im::auth::UserInfo* _msg = _internal_mutable_m_user();
  // @@protoc_insertion_point(field_mutable:wuk.im.auth.LoginResponse.m_user)
  return _msg;
}
inline void LoginResponse::set_allocated_m_user(::wuk::im::auth::UserInfo* m_user) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.m_user_;
  }
  if (m_user) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(m_user);
    if (message_arena != submessage_arena) {
      m_user = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m_user, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.m_user_ = m_user;
  // @@protoc_insertion_point(field_set_allocated:wuk.im.auth.LoginResponse.m_user)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace auth
}  // namespace im
}  // namespace wuk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::wuk::im::auth::ResponseType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::wuk::im::auth::ResponseType>() {
  return ::wuk::im::auth::ResponseType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_login_5fresponse_2eproto
