// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "packet.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
namespace wuk {
namespace im {
namespace msg {
class Message;
struct MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace msg
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> ::wuk::im::msg::Message* Arena::CreateMaybeMessage<::wuk::im::msg::Message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wuk {
namespace im {
namespace msg {

enum MessageType : int {
  MESSAGE_TYPE_TEXT = 0,
  MESSAGE_TYPE_IMAGE = 1,
  MESSAGE_TYPE_VOICE = 2,
  MESSAGE_TYPE_FILE = 4,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = MESSAGE_TYPE_TEXT;
constexpr MessageType MessageType_MAX = MESSAGE_TYPE_FILE;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
enum ChatType : int {
  CHAT_TYPE_PRIVATE = 0,
  CHAT_TYPE_GROUP = 1,
  CHAT_TYPE_ONE2ONE = 2,
  ChatType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ChatType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ChatType_IsValid(int value);
constexpr ChatType ChatType_MIN = CHAT_TYPE_PRIVATE;
constexpr ChatType ChatType_MAX = CHAT_TYPE_ONE2ONE;
constexpr int ChatType_ARRAYSIZE = ChatType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ChatType_descriptor();
template<typename T>
inline const std::string& ChatType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ChatType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ChatType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ChatType_descriptor(), enum_t_value);
}
inline bool ChatType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ChatType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ChatType>(
    ChatType_descriptor(), name, value);
}
// ===================================================================

class Message final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wuk.im.msg.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() override;
  explicit PROTOBUF_CONSTEXPR Message(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Message& default_instance() {
    return *internal_default_instance();
  }
  enum TargetCase {
    kMRecipient = 5,
    kMGroup = 6,
    TARGET_NOT_SET = 0,
  };

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Message& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Message& from) {
    Message::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wuk.im.msg.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMContentFieldNumber = 7,
    kMBaseFieldNumber = 1,
    kMMsgTypeFieldNumber = 2,
    kMChatTypeFieldNumber = 3,
    kMSenderFieldNumber = 4,
    kMRecipientFieldNumber = 5,
    kMGroupFieldNumber = 6,
  };
  // bytes m_content = 7;
  void clear_m_content();
  const std::string& m_content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_m_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_m_content();
  PROTOBUF_NODISCARD std::string* release_m_content();
  void set_allocated_m_content(std::string* m_content);
  private:
  const std::string& _internal_m_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_content(const std::string& value);
  std::string* _internal_mutable_m_content();
  public:

  // .wuk.im.base.BaseRequest m_base = 1;
  bool has_m_base() const;
  private:
  bool _internal_has_m_base() const;
  public:
  void clear_m_base();
  const ::wuk::im::base::BaseRequest& m_base() const;
  PROTOBUF_NODISCARD ::wuk::im::base::BaseRequest* release_m_base();
  ::wuk::im::base::BaseRequest* mutable_m_base();
  void set_allocated_m_base(::wuk::im::base::BaseRequest* m_base);
  private:
  const ::wuk::im::base::BaseRequest& _internal_m_base() const;
  ::wuk::im::base::BaseRequest* _internal_mutable_m_base();
  public:
  void unsafe_arena_set_allocated_m_base(
      ::wuk::im::base::BaseRequest* m_base);
  ::wuk::im::base::BaseRequest* unsafe_arena_release_m_base();

  // .wuk.im.msg.MessageType m_msg_type = 2;
  void clear_m_msg_type();
  ::wuk::im::msg::MessageType m_msg_type() const;
  void set_m_msg_type(::wuk::im::msg::MessageType value);
  private:
  ::wuk::im::msg::MessageType _internal_m_msg_type() const;
  void _internal_set_m_msg_type(::wuk::im::msg::MessageType value);
  public:

  // .wuk.im.msg.ChatType m_chat_type = 3;
  void clear_m_chat_type();
  ::wuk::im::msg::ChatType m_chat_type() const;
  void set_m_chat_type(::wuk::im::msg::ChatType value);
  private:
  ::wuk::im::msg::ChatType _internal_m_chat_type() const;
  void _internal_set_m_chat_type(::wuk::im::msg::ChatType value);
  public:

  // uint64 m_sender = 4;
  void clear_m_sender();
  uint64_t m_sender() const;
  void set_m_sender(uint64_t value);
  private:
  uint64_t _internal_m_sender() const;
  void _internal_set_m_sender(uint64_t value);
  public:

  // uint64 m_recipient = 5;
  bool has_m_recipient() const;
  private:
  bool _internal_has_m_recipient() const;
  public:
  void clear_m_recipient();
  uint64_t m_recipient() const;
  void set_m_recipient(uint64_t value);
  private:
  uint64_t _internal_m_recipient() const;
  void _internal_set_m_recipient(uint64_t value);
  public:

  // uint64 m_group = 6;
  bool has_m_group() const;
  private:
  bool _internal_has_m_group() const;
  public:
  void clear_m_group();
  uint64_t m_group() const;
  void set_m_group(uint64_t value);
  private:
  uint64_t _internal_m_group() const;
  void _internal_set_m_group(uint64_t value);
  public:

  void clear_target();
  TargetCase target_case() const;
  // @@protoc_insertion_point(class_scope:wuk.im.msg.Message)
 private:
  class _Internal;
  void set_has_m_recipient();
  void set_has_m_group();

  inline bool has_target() const;
  inline void clear_has_target();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_content_;
    ::wuk::im::base::BaseRequest* m_base_;
    int m_msg_type_;
    int m_chat_type_;
    uint64_t m_sender_;
    union TargetUnion {
      constexpr TargetUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      uint64_t m_recipient_;
      uint64_t m_group_;
    } target_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Message

// .wuk.im.base.BaseRequest m_base = 1;
inline bool Message::_internal_has_m_base() const {
  return this != internal_default_instance() && _impl_.m_base_ != nullptr;
}
inline bool Message::has_m_base() const {
  return _internal_has_m_base();
}
inline const ::wuk::im::base::BaseRequest& Message::_internal_m_base() const {
  const ::wuk::im::base::BaseRequest* p = _impl_.m_base_;
  return p != nullptr ? *p : reinterpret_cast<const ::wuk::im::base::BaseRequest&>(
      ::wuk::im::base::_BaseRequest_default_instance_);
}
inline const ::wuk::im::base::BaseRequest& Message::m_base() const {
  // @@protoc_insertion_point(field_get:wuk.im.msg.Message.m_base)
  return _internal_m_base();
}
inline void Message::unsafe_arena_set_allocated_m_base(
    ::wuk::im::base::BaseRequest* m_base) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.m_base_);
  }
  _impl_.m_base_ = m_base;
  if (m_base) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wuk.im.msg.Message.m_base)
}
inline ::wuk::im::base::BaseRequest* Message::release_m_base() {
  
  ::wuk::im::base::BaseRequest* temp = _impl_.m_base_;
  _impl_.m_base_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wuk::im::base::BaseRequest* Message::unsafe_arena_release_m_base() {
  // @@protoc_insertion_point(field_release:wuk.im.msg.Message.m_base)
  
  ::wuk::im::base::BaseRequest* temp = _impl_.m_base_;
  _impl_.m_base_ = nullptr;
  return temp;
}
inline ::wuk::im::base::BaseRequest* Message::_internal_mutable_m_base() {
  
  if (_impl_.m_base_ == nullptr) {
    auto* p = CreateMaybeMessage<::wuk::im::base::BaseRequest>(GetArenaForAllocation());
    _impl_.m_base_ = p;
  }
  return _impl_.m_base_;
}
inline ::wuk::im::base::BaseRequest* Message::mutable_m_base() {
  ::wuk::im::base::BaseRequest* _msg = _internal_mutable_m_base();
  // @@protoc_insertion_point(field_mutable:wuk.im.msg.Message.m_base)
  return _msg;
}
inline void Message::set_allocated_m_base(::wuk::im::base::BaseRequest* m_base) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.m_base_);
  }
  if (m_base) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(m_base));
    if (message_arena != submessage_arena) {
      m_base = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m_base, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.m_base_ = m_base;
  // @@protoc_insertion_point(field_set_allocated:wuk.im.msg.Message.m_base)
}

// .wuk.im.msg.MessageType m_msg_type = 2;
inline void Message::clear_m_msg_type() {
  _impl_.m_msg_type_ = 0;
}
inline ::wuk::im::msg::MessageType Message::_internal_m_msg_type() const {
  return static_cast< ::wuk::im::msg::MessageType >(_impl_.m_msg_type_);
}
inline ::wuk::im::msg::MessageType Message::m_msg_type() const {
  // @@protoc_insertion_point(field_get:wuk.im.msg.Message.m_msg_type)
  return _internal_m_msg_type();
}
inline void Message::_internal_set_m_msg_type(::wuk::im::msg::MessageType value) {
  
  _impl_.m_msg_type_ = value;
}
inline void Message::set_m_msg_type(::wuk::im::msg::MessageType value) {
  _internal_set_m_msg_type(value);
  // @@protoc_insertion_point(field_set:wuk.im.msg.Message.m_msg_type)
}

// .wuk.im.msg.ChatType m_chat_type = 3;
inline void Message::clear_m_chat_type() {
  _impl_.m_chat_type_ = 0;
}
inline ::wuk::im::msg::ChatType Message::_internal_m_chat_type() const {
  return static_cast< ::wuk::im::msg::ChatType >(_impl_.m_chat_type_);
}
inline ::wuk::im::msg::ChatType Message::m_chat_type() const {
  // @@protoc_insertion_point(field_get:wuk.im.msg.Message.m_chat_type)
  return _internal_m_chat_type();
}
inline void Message::_internal_set_m_chat_type(::wuk::im::msg::ChatType value) {
  
  _impl_.m_chat_type_ = value;
}
inline void Message::set_m_chat_type(::wuk::im::msg::ChatType value) {
  _internal_set_m_chat_type(value);
  // @@protoc_insertion_point(field_set:wuk.im.msg.Message.m_chat_type)
}

// uint64 m_sender = 4;
inline void Message::clear_m_sender() {
  _impl_.m_sender_ = uint64_t{0u};
}
inline uint64_t Message::_internal_m_sender() const {
  return _impl_.m_sender_;
}
inline uint64_t Message::m_sender() const {
  // @@protoc_insertion_point(field_get:wuk.im.msg.Message.m_sender)
  return _internal_m_sender();
}
inline void Message::_internal_set_m_sender(uint64_t value) {
  
  _impl_.m_sender_ = value;
}
inline void Message::set_m_sender(uint64_t value) {
  _internal_set_m_sender(value);
  // @@protoc_insertion_point(field_set:wuk.im.msg.Message.m_sender)
}

// uint64 m_recipient = 5;
inline bool Message::_internal_has_m_recipient() const {
  return target_case() == kMRecipient;
}
inline bool Message::has_m_recipient() const {
  return _internal_has_m_recipient();
}
inline void Message::set_has_m_recipient() {
  _impl_._oneof_case_[0] = kMRecipient;
}
inline void Message::clear_m_recipient() {
  if (_internal_has_m_recipient()) {
    _impl_.target_.m_recipient_ = uint64_t{0u};
    clear_has_target();
  }
}
inline uint64_t Message::_internal_m_recipient() const {
  if (_internal_has_m_recipient()) {
    return _impl_.target_.m_recipient_;
  }
  return uint64_t{0u};
}
inline void Message::_internal_set_m_recipient(uint64_t value) {
  if (!_internal_has_m_recipient()) {
    clear_target();
    set_has_m_recipient();
  }
  _impl_.target_.m_recipient_ = value;
}
inline uint64_t Message::m_recipient() const {
  // @@protoc_insertion_point(field_get:wuk.im.msg.Message.m_recipient)
  return _internal_m_recipient();
}
inline void Message::set_m_recipient(uint64_t value) {
  _internal_set_m_recipient(value);
  // @@protoc_insertion_point(field_set:wuk.im.msg.Message.m_recipient)
}

// uint64 m_group = 6;
inline bool Message::_internal_has_m_group() const {
  return target_case() == kMGroup;
}
inline bool Message::has_m_group() const {
  return _internal_has_m_group();
}
inline void Message::set_has_m_group() {
  _impl_._oneof_case_[0] = kMGroup;
}
inline void Message::clear_m_group() {
  if (_internal_has_m_group()) {
    _impl_.target_.m_group_ = uint64_t{0u};
    clear_has_target();
  }
}
inline uint64_t Message::_internal_m_group() const {
  if (_internal_has_m_group()) {
    return _impl_.target_.m_group_;
  }
  return uint64_t{0u};
}
inline void Message::_internal_set_m_group(uint64_t value) {
  if (!_internal_has_m_group()) {
    clear_target();
    set_has_m_group();
  }
  _impl_.target_.m_group_ = value;
}
inline uint64_t Message::m_group() const {
  // @@protoc_insertion_point(field_get:wuk.im.msg.Message.m_group)
  return _internal_m_group();
}
inline void Message::set_m_group(uint64_t value) {
  _internal_set_m_group(value);
  // @@protoc_insertion_point(field_set:wuk.im.msg.Message.m_group)
}

// bytes m_content = 7;
inline void Message::clear_m_content() {
  _impl_.m_content_.ClearToEmpty();
}
inline const std::string& Message::m_content() const {
  // @@protoc_insertion_point(field_get:wuk.im.msg.Message.m_content)
  return _internal_m_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_m_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.m_content_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wuk.im.msg.Message.m_content)
}
inline std::string* Message::mutable_m_content() {
  std::string* _s = _internal_mutable_m_content();
  // @@protoc_insertion_point(field_mutable:wuk.im.msg.Message.m_content)
  return _s;
}
inline const std::string& Message::_internal_m_content() const {
  return _impl_.m_content_.Get();
}
inline void Message::_internal_set_m_content(const std::string& value) {
  
  _impl_.m_content_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_m_content() {
  
  return _impl_.m_content_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_m_content() {
  // @@protoc_insertion_point(field_release:wuk.im.msg.Message.m_content)
  return _impl_.m_content_.Release();
}
inline void Message::set_allocated_m_content(std::string* m_content) {
  if (m_content != nullptr) {
    
  } else {
    
  }
  _impl_.m_content_.SetAllocated(m_content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.m_content_.IsDefault()) {
    _impl_.m_content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wuk.im.msg.Message.m_content)
}

inline bool Message::has_target() const {
  return target_case() != TARGET_NOT_SET;
}
inline void Message::clear_has_target() {
  _impl_._oneof_case_[0] = TARGET_NOT_SET;
}
inline Message::TargetCase Message::target_case() const {
  return Message::TargetCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msg
}  // namespace im
}  // namespace wuk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::wuk::im::msg::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::wuk::im::msg::MessageType>() {
  return ::wuk::im::msg::MessageType_descriptor();
}
template <> struct is_proto_enum< ::wuk::im::msg::ChatType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::wuk::im::msg::ChatType>() {
  return ::wuk::im::msg::ChatType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
