// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_packet_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_packet_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_packet_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_packet_2eproto;
namespace wuk {
namespace im {
namespace base {
class BaseRequest;
struct BaseRequestDefaultTypeInternal;
extern BaseRequestDefaultTypeInternal _BaseRequest_default_instance_;
}  // namespace base
}  // namespace im
}  // namespace wuk
PROTOBUF_NAMESPACE_OPEN
template<> ::wuk::im::base::BaseRequest* Arena::CreateMaybeMessage<::wuk::im::base::BaseRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wuk {
namespace im {
namespace base {

enum RequestType : int {
  REQUEST_TYPE_HEARTBEAT = 0,
  REQUEST_TYPE_LOGIN = 10,
  REQUEST_TYPE_REGISTER = 11,
  REQUEST_TYPE_FIND_PWD = 12,
  REQUEST_TYPE_MESSAGE = 20,
  RequestType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RequestType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RequestType_IsValid(int value);
constexpr RequestType RequestType_MIN = REQUEST_TYPE_HEARTBEAT;
constexpr RequestType RequestType_MAX = REQUEST_TYPE_MESSAGE;
constexpr int RequestType_ARRAYSIZE = RequestType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RequestType_descriptor();
template<typename T>
inline const std::string& RequestType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RequestType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RequestType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RequestType_descriptor(), enum_t_value);
}
inline bool RequestType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RequestType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RequestType>(
    RequestType_descriptor(), name, value);
}
// ===================================================================

class BaseRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wuk.im.base.BaseRequest) */ {
 public:
  inline BaseRequest() : BaseRequest(nullptr) {}
  ~BaseRequest() override;
  explicit PROTOBUF_CONSTEXPR BaseRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BaseRequest(const BaseRequest& from);
  BaseRequest(BaseRequest&& from) noexcept
    : BaseRequest() {
    *this = ::std::move(from);
  }

  inline BaseRequest& operator=(const BaseRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BaseRequest& operator=(BaseRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BaseRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BaseRequest* internal_default_instance() {
    return reinterpret_cast<const BaseRequest*>(
               &_BaseRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BaseRequest& a, BaseRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BaseRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BaseRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BaseRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BaseRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BaseRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BaseRequest& from) {
    BaseRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BaseRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wuk.im.base.BaseRequest";
  }
  protected:
  explicit BaseRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMTypeFieldNumber = 1,
    kMIdFieldNumber = 2,
    kMSequenceFieldNumber = 3,
    kMSegmentFieldNumber = 4,
    kMTimestampFieldNumber = 6,
    kMProtoVerFieldNumber = 5,
  };
  // .wuk.im.base.RequestType m_type = 1;
  void clear_m_type();
  ::wuk::im::base::RequestType m_type() const;
  void set_m_type(::wuk::im::base::RequestType value);
  private:
  ::wuk::im::base::RequestType _internal_m_type() const;
  void _internal_set_m_type(::wuk::im::base::RequestType value);
  public:

  // uint32 m_id = 2;
  void clear_m_id();
  uint32_t m_id() const;
  void set_m_id(uint32_t value);
  private:
  uint32_t _internal_m_id() const;
  void _internal_set_m_id(uint32_t value);
  public:

  // uint32 m_sequence = 3;
  void clear_m_sequence();
  uint32_t m_sequence() const;
  void set_m_sequence(uint32_t value);
  private:
  uint32_t _internal_m_sequence() const;
  void _internal_set_m_sequence(uint32_t value);
  public:

  // uint32 m_segment = 4;
  void clear_m_segment();
  uint32_t m_segment() const;
  void set_m_segment(uint32_t value);
  private:
  uint32_t _internal_m_segment() const;
  void _internal_set_m_segment(uint32_t value);
  public:

  // uint64 m_timestamp = 6;
  void clear_m_timestamp();
  uint64_t m_timestamp() const;
  void set_m_timestamp(uint64_t value);
  private:
  uint64_t _internal_m_timestamp() const;
  void _internal_set_m_timestamp(uint64_t value);
  public:

  // uint32 m_proto_ver = 5;
  void clear_m_proto_ver();
  uint32_t m_proto_ver() const;
  void set_m_proto_ver(uint32_t value);
  private:
  uint32_t _internal_m_proto_ver() const;
  void _internal_set_m_proto_ver(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:wuk.im.base.BaseRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int m_type_;
    uint32_t m_id_;
    uint32_t m_sequence_;
    uint32_t m_segment_;
    uint64_t m_timestamp_;
    uint32_t m_proto_ver_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BaseRequest

// .wuk.im.base.RequestType m_type = 1;
inline void BaseRequest::clear_m_type() {
  _impl_.m_type_ = 0;
}
inline ::wuk::im::base::RequestType BaseRequest::_internal_m_type() const {
  return static_cast< ::wuk::im::base::RequestType >(_impl_.m_type_);
}
inline ::wuk::im::base::RequestType BaseRequest::m_type() const {
  // @@protoc_insertion_point(field_get:wuk.im.base.BaseRequest.m_type)
  return _internal_m_type();
}
inline void BaseRequest::_internal_set_m_type(::wuk::im::base::RequestType value) {
  
  _impl_.m_type_ = value;
}
inline void BaseRequest::set_m_type(::wuk::im::base::RequestType value) {
  _internal_set_m_type(value);
  // @@protoc_insertion_point(field_set:wuk.im.base.BaseRequest.m_type)
}

// uint32 m_id = 2;
inline void BaseRequest::clear_m_id() {
  _impl_.m_id_ = 0u;
}
inline uint32_t BaseRequest::_internal_m_id() const {
  return _impl_.m_id_;
}
inline uint32_t BaseRequest::m_id() const {
  // @@protoc_insertion_point(field_get:wuk.im.base.BaseRequest.m_id)
  return _internal_m_id();
}
inline void BaseRequest::_internal_set_m_id(uint32_t value) {
  
  _impl_.m_id_ = value;
}
inline void BaseRequest::set_m_id(uint32_t value) {
  _internal_set_m_id(value);
  // @@protoc_insertion_point(field_set:wuk.im.base.BaseRequest.m_id)
}

// uint32 m_sequence = 3;
inline void BaseRequest::clear_m_sequence() {
  _impl_.m_sequence_ = 0u;
}
inline uint32_t BaseRequest::_internal_m_sequence() const {
  return _impl_.m_sequence_;
}
inline uint32_t BaseRequest::m_sequence() const {
  // @@protoc_insertion_point(field_get:wuk.im.base.BaseRequest.m_sequence)
  return _internal_m_sequence();
}
inline void BaseRequest::_internal_set_m_sequence(uint32_t value) {
  
  _impl_.m_sequence_ = value;
}
inline void BaseRequest::set_m_sequence(uint32_t value) {
  _internal_set_m_sequence(value);
  // @@protoc_insertion_point(field_set:wuk.im.base.BaseRequest.m_sequence)
}

// uint32 m_segment = 4;
inline void BaseRequest::clear_m_segment() {
  _impl_.m_segment_ = 0u;
}
inline uint32_t BaseRequest::_internal_m_segment() const {
  return _impl_.m_segment_;
}
inline uint32_t BaseRequest::m_segment() const {
  // @@protoc_insertion_point(field_get:wuk.im.base.BaseRequest.m_segment)
  return _internal_m_segment();
}
inline void BaseRequest::_internal_set_m_segment(uint32_t value) {
  
  _impl_.m_segment_ = value;
}
inline void BaseRequest::set_m_segment(uint32_t value) {
  _internal_set_m_segment(value);
  // @@protoc_insertion_point(field_set:wuk.im.base.BaseRequest.m_segment)
}

// uint32 m_proto_ver = 5;
inline void BaseRequest::clear_m_proto_ver() {
  _impl_.m_proto_ver_ = 0u;
}
inline uint32_t BaseRequest::_internal_m_proto_ver() const {
  return _impl_.m_proto_ver_;
}
inline uint32_t BaseRequest::m_proto_ver() const {
  // @@protoc_insertion_point(field_get:wuk.im.base.BaseRequest.m_proto_ver)
  return _internal_m_proto_ver();
}
inline void BaseRequest::_internal_set_m_proto_ver(uint32_t value) {
  
  _impl_.m_proto_ver_ = value;
}
inline void BaseRequest::set_m_proto_ver(uint32_t value) {
  _internal_set_m_proto_ver(value);
  // @@protoc_insertion_point(field_set:wuk.im.base.BaseRequest.m_proto_ver)
}

// uint64 m_timestamp = 6;
inline void BaseRequest::clear_m_timestamp() {
  _impl_.m_timestamp_ = uint64_t{0u};
}
inline uint64_t BaseRequest::_internal_m_timestamp() const {
  return _impl_.m_timestamp_;
}
inline uint64_t BaseRequest::m_timestamp() const {
  // @@protoc_insertion_point(field_get:wuk.im.base.BaseRequest.m_timestamp)
  return _internal_m_timestamp();
}
inline void BaseRequest::_internal_set_m_timestamp(uint64_t value) {
  
  _impl_.m_timestamp_ = value;
}
inline void BaseRequest::set_m_timestamp(uint64_t value) {
  _internal_set_m_timestamp(value);
  // @@protoc_insertion_point(field_set:wuk.im.base.BaseRequest.m_timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace base
}  // namespace im
}  // namespace wuk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::wuk::im::base::RequestType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::wuk::im::base::RequestType>() {
  return ::wuk::im::base::RequestType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_packet_2eproto
